const L = require('D:/work/statemanager-cfb/tests/browser/_gen_lib.cjs');
const H = L.H;
(async () => {
  const { browser, page } = await H.open({ port: 8855 });
  const out = {};
  out.atStep4 = await L.walkToQubits(page);
  await L.setInput(page, '#gen-qubit-count', '4');
  await H.sleep(1200);
  await L.evClick(page, '#gen-next'); await H.sleep(1200);
  out.atStep5 = await L.info(page);
  await L.evClick(page, '#gen-allocate-btn');
  await H.sleep(9000);
  out.allocStatus = await page.$eval('#gen-allocate-status', e => e.innerText);
  out.issues = await page.$eval('#gen-wiring-issues', e => e.innerText.slice(0, 500));
  out.tableRows = await page.$$eval('#gen-wiring-table tr', els => els.length);
  out.tableHead = await page.$eval('#gen-wiring-table', e => e.innerText.slice(0, 700)).catch(() => 'ERR');
  out.diagram = await page.$eval('#gen-wiring-diagram', e => e.innerText.slice(0, 200));
  await H.shot(page, 'gen_07_wiring');
  await L.evClick(page, '#gen-next'); await H.sleep(2500);
  out.atStep6 = await L.info(page);
  out.popUnits = await page.$eval('#gen-pop-units', e => e.innerText.replace(/\n/g, ' | ').slice(0, 600)).catch(() => 'ERR');
  out.popQubitHead = await page.$eval('#gen-pop-qubit', e => e.innerText.slice(0, 500)).catch(() => 'ERR');
  await H.shot(page, 'gen_08_populate');
  out.errors = H.errors(page);
  console.log(JSON.stringify(out, null, 1));
  await browser.close();
})();
