"""The key manual's first source (2026-08-27): per-field descriptions parsed
from the env classes' own docstrings (quam / quam_builder write Google-style
Args: / Attributes: sections). Pins the parser on a synthetic hierarchy, and
-- in the customer env -- that the real FluxLine.joint_offset line comes
through verbatim. Absent text stays absent: no paraphrase, no guess."""
from __future__ import annotations

import dataclasses

import pytest

from quam_state_manager.generator import probe_state_schema as probe


class _Base:
    """Base component.

    Args:
        operations (Dict[str, Pulse]): A dictionary of pulses to be played on this
            channel. The key is the pulse label (e.g. "X90") and value is a Pulse.
        id (str, int): The id of the channel, used to generate the name.
            Can be a string, or an integer in which case it will add
            `Channel._default_label`.
        sticky (Sticky): Optional sticky parameters.

    Returns:
        nothing relevant: this must NOT be read as a field
    """


class _Line(_Base):
    """QUAM component for a flux line.

    Attributes:
        independent_offset (float): the flux bias corresponding to the resonator maximum frequency when all the active
            qubits are not interacting (min offset) in V.
        joint_offset (float): the flux bias at the joint operating point in V.
        id: overridden description in the subclass.
    """


@dataclasses.dataclass
class _NoDoc:
    x: int = 0


class TestParser:
    def test_entries_continuations_and_sections(self):
        docs = probe._parse_field_docs(_Base.__doc__)
        assert docs["operations"].startswith("A dictionary of pulses") and "value is a Pulse." in docs["operations"]
        assert "`Channel._default_label`" in docs["id"], "continuation lines join the entry"
        assert docs["sticky"] == "Optional sticky parameters."
        assert "nothing" not in docs and "Returns" not in docs, "other sections are not fields"

    def test_mro_walk_keeps_the_defining_class_text_and_lets_a_subclass_override(self):
        summary, docs = probe._class_docs(_Line)
        assert summary == "QUAM component for a flux line."
        assert docs["joint_offset"] == "the flux bias at the joint operating point in V."
        assert docs["independent_offset"].endswith("(min offset) in V.")
        assert docs["operations"].startswith("A dictionary"), "inherited field keeps its base description"
        assert docs["id"] == "overridden description in the subclass."

    def test_an_autogenerated_dataclass_docstring_is_not_documentation(self):
        summary, docs = probe._class_docs(_NoDoc)
        assert summary is None and docs == {}


def test_the_real_flux_line_docstring_comes_through():
    """Runs where the customer env is importable (the cqt pytest env)."""
    pytest.importorskip("quam_builder")
    # docs/141 4h: the catalogue enumerates the env's component classes
    # without walking unknown packages -- quam's own components and
    # quam_builder's superconducting architecture, plus the subclass closure
    cat = probe.enumerate_catalog([])
    assert len(cat) >= 50, len(cat)
    assert cat.get("quam.components.pulses.SquarePulse") == "Pulses"
    assert cat.get("quam.components.channels.InOutIQChannel") == "Channels"
    assert not any(p.startswith("quam.core") for p in cat), "core base classes are not components"
    assert all(("." in p and not p.rsplit(".", 1)[-1].startswith("_")) for p in cat)
    from quam_builder.architecture.superconducting.components.flux_line import FluxLine
    entry = probe._dump_class(f"{FluxLine.__module__}.FluxLine")
    assert entry["importable"] and entry["fields"]
    assert entry["doc"] and "flux line" in entry["doc"].lower()
    jo = entry["fields"]["joint_offset"]
    assert "flux bias" in (jo.get("doc") or ""), jo
    # an inherited channel field (operations) still carries its base's text
    assert entry["fields"]["operations"].get("doc")
    # a PORT class has no docstring upstream: its fields get NO doc key, not a guess
    from quam.components.ports.analog_outputs import MWFEMAnalogOutputPort
    port = probe._dump_class(f"{MWFEMAnalogOutputPort.__module__}.MWFEMAnalogOutputPort")
    assert port["importable"] and port["fields"]
    assert port["doc"] is None
    assert all("doc" not in r for r in port["fields"].values()), "silence, never a paraphrase"
