"""Lab-faithful figure generation (docs/78 D-11, P0e).

The vision judge is fed the figure the physicist sees: the lab's own
``calibration_utils/<util>/plotting.py`` output, regenerated by
``generator/run_figure_gen.py`` inside the customer env — never an SM
re-render (docs/78 §4.2: SM's Interactive re-render of the flux families is
transposed; feeding a judge a rotated arch would test the wrong signature).

Per-family figure dispatch lives HERE (SM owns the registry; the env-side
script receives everything explicitly on the CLI so the two can't drift into
guessing). ``FIGSPEC`` mirrors what each node saves as its primary
``figures[...]`` key (recon 2026-08-06):

* every family's primary sheet is ``plot_raw_data_with_fit`` except node 03's
  ``plot_raw_amplitude_with_fit``;
* the vs_power families save under key ``power_dbm`` (the rest ``amplitude``);
* node 10 draws on a ``QubitPairGrid`` and takes PAIR objects as the second
  argument (``arg2="pairs"``); every other family takes the measured qubits.

Every result carries env + ``lib_versions`` + ``gate_hash`` (docs/78 D-13.3 —
a figure without its provenance is not evidence).
"""
from __future__ import annotations

import json
import logging
import subprocess
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)

# family -> how to regenerate its primary (judge-facing) figure.
FIGSPEC: dict[str, dict] = {
    "resonator_spectroscopy": {
        "key": "amplitude", "fn": "plot_raw_amplitude_with_fit", "arg2": "qubits"},
    "resonator_spectroscopy_vs_power": {
        "key": "power_dbm", "fn": "plot_raw_data_with_fit", "arg2": "qubits"},
    "resonator_spectroscopy_vs_flux": {
        "key": "amplitude", "fn": "plot_raw_data_with_fit", "arg2": "qubits"},
    "resonator_spectroscopy_vs_coupler_flux": {
        "key": "amplitude", "fn": "plot_raw_data_with_fit", "arg2": "qubits"},
    "qubit_spectroscopy": {
        "key": "amplitude", "fn": "plot_raw_data_with_fit", "arg2": "qubits"},
    "qubit_spectroscopy_vs_power": {
        "key": "power_dbm", "fn": "plot_raw_data_with_fit", "arg2": "qubits"},
    "qubit_spectroscopy_vs_flux": {
        "key": "amplitude", "fn": "plot_raw_data_with_fit", "arg2": "qubits"},
    "qubit_spectroscopy_vs_coupler_flux": {
        "key": "amplitude", "fn": "plot_raw_data_with_fit", "arg2": "pairs"},
    "power_rabi": {
        "key": "amplitude", "fn": "plot_raw_data_with_fit", "arg2": "qubits"},
}


def generate(run_folder, *, family: str, env: str | None = None,
             envs: list[str] | None = None, source_root: str | None = None,
             roots: list | None = None,
             instance_path=None, targets: list[str] | None = None,
             fit_source: str = "fresh", override_fit: dict | None = None,
             out_dir=None, timeout: int = 420) -> dict:
    """Regenerate ``run_folder``'s primary figure with the lab's plotting.

    ``targets=None`` → the full sheet (fidelity-check input, docs/78 D-11.2);
    ``targets=[...]`` → one single-panel figure per target (the judge feed,
    D-11.1). ``env`` may be given directly, or chosen from ``envs`` via the
    envmatrix probe (docs/78 D-13). ``override_fit`` = ``{target: {var: value}}``
    manufactures a wrong-fit figure (D-7 leniency calibration ONLY).

    Returns ``{ok, figures: [{target, path}], errors, env, probes,
    lib_versions, gate_hash, fit_source}``.
    """
    from quam_state_manager.core.fit_audit import FAMILIES

    # what the CALLER asked for, kept separate from what was actually used:
    # on the no-compatible-env path `source_root` is rebound to None, and a
    # context built from that would report "the env's installed analysis" —
    # naming an analysis that never ran (docs/78 §17 B3: the stamp exists to
    # stop exactly this kind of confident blank).
    requested_root = source_root

    def _fail(stage, trace, *, env=None, probes=None, source_root=None,
              root_kind=None, root_rev=None):
        """Every return carries the SAME keys — a caller reading `source_root`
        or `lib_versions` must not KeyError on the failure path."""
        from quam_state_manager.core.autofit import verification

        return {"ok": False, "figures": [], "errors": [{"stage": stage,
                                                        "trace": trace}],
                "env": env, "probes": probes or [], "source_root": source_root,
                "root_kind": root_kind, "root_rev": root_rev,
                "lib_versions": {}, "gate_hash": None,
                "context": verification.for_lab_replay(
                    env=env, source_root=source_root or requested_root,
                    root_kind=root_kind or (None if env is None else "installed"),
                    root_rev=root_rev, run_folder=run_folder).as_dict(),
                "fit_source": fit_source, "out_dir": str(out_dir) if out_dir else None}

    spec = FIGSPEC.get(family)
    fam = FAMILIES.get(family)
    if spec is None or fam is None:
        return _fail("family", f"family {family!r} has no figure spec", env=env,
                     source_root=source_root)

    probes, root_kind, root_rev = [], None, None
    if env is None:
        from quam_state_manager.core.autofit import envmatrix
        choice = envmatrix.choose_context(
            run_folder, envs or [], roots or [source_root],
            instance_path=instance_path)
        env, probes = choice["env"], choice["probes"]
        source_root = choice["source_root"]
        root_kind, root_rev = choice["root_kind"], choice["root_rev"]
        if env is None:
            return _fail("env",
                         "no compatible (env, analysis tree) for this run's "
                         "generation — "
                         + "; ".join(f"{p['env']}: {p['message']}"
                                     for p in probes),
                         probes=probes)

    if out_dir is None:
        # docs/101 C2: a POSIX tempdir (/tmp/…) handed to a WINDOWS .exe
        # interpreter through the supported WSL bridge is invisible to the
        # child — it recreates the literal path under its own drive and the
        # parent 404s every figure. When the chosen env is a Windows
        # interpreter and we are not on Windows, allocate the workdir
        # somewhere both dialects can reach (under the instance dir when
        # known, else the run folder's parent is NOT ours to write — fall
        # back to the source of the bridge, /mnt-visible TMP).
        _tmp_root = None
        if os.name != "nt" and str(env).lower().endswith(".exe"):
            if instance_path:
                _tmp_root = str(Path(instance_path) / "figgen_tmp")
                Path(_tmp_root).mkdir(parents=True, exist_ok=True)
                # docs/101 C3: these dirs outlive the call (the caller reads
                # the PNGs from the returned paths), so sweep day-old
                # siblings instead of leaking one per judge call forever.
                import shutil as _sh
                import time as _t
                _cut = _t.time() - 86400
                for _d in Path(_tmp_root).glob("sm_figgen_*"):
                    try:
                        if _d.stat().st_mtime < _cut:
                            _sh.rmtree(_d, ignore_errors=True)
                    except OSError:
                        pass
        out_dir = tempfile.mkdtemp(prefix="sm_figgen_", dir=_tmp_root)
    else:
        # the override-fit temp file is written HERE; the env-side script's own
        # makedirs runs too late for it
        Path(out_dir).mkdir(parents=True, exist_ok=True)
    envelope = _spawn(env, run_folder, spec, fam["util"], source_root,
                      targets, fit_source, override_fit, out_dir, timeout)
    from quam_state_manager.core.autofit import verification

    figures = envelope.get("figures") or []
    errors = envelope.get("errors") or []
    out = {"ok": bool(figures) and not errors, "figures": figures,
           "errors": errors, "env": env, "probes": probes,
           "source_root": source_root, "root_kind": root_kind,
           "root_rev": root_rev,
           "lib_versions": envelope.get("lib_versions") or {},
           "gate_hash": envelope.get("gate_hash"),
           "fit_source": fit_source, "out_dir": str(out_dir)}
    # the same shape fit_audit and the engine stamp (docs/78 §17 B3) — this
    # path already carried all four axes, so here it is only a re-expression;
    # having ONE dict is what lets a reader compare across the three.
    out["context"] = verification.from_figure_gen(
        out, run_folder=run_folder).as_dict()
    return out


def _spawn(env, run_folder, spec, util, source_root, targets, fit_source,
           override_fit, out_dir, timeout) -> dict:
    from quam_state_manager.core.config_generator import _script_path
    from quam_state_manager.core.fit_audit import _pth

    args = [env, _pth(env, str(_script_path("run_figure_gen.py"))),
            "--run", _pth(env, str(run_folder)),
            "--util", util,
            "--plot-fn", spec["fn"], "--figure-key", spec["key"],
            "--arg2", spec["arg2"],
            "--fit-source", fit_source,
            "--out-dir", _pth(env, str(out_dir))]
    if source_root:
        args += ["--source-root", _pth(env, str(source_root))]
    if targets:
        args += ["--targets", ",".join(targets)]
    ov_file = None
    try:
        if override_fit:
            fd = tempfile.NamedTemporaryFile("w", suffix=".json", dir=out_dir,
                                             delete=False, encoding="utf-8")
            with fd:
                json.dump(override_fit, fd)
            ov_file = fd.name
            args += ["--override-fit", _pth(env, ov_file)]
        try:
            proc = subprocess.run(args, capture_output=True, text=True,
                                  encoding="utf-8", errors="replace",
                                  timeout=timeout)
        except subprocess.TimeoutExpired:
            return {"errors": [{"stage": "timeout",
                                "trace": f"figure generation exceeded {timeout}s"}]}
        except OSError as e:
            return {"errors": [{"stage": "spawn", "trace": str(e)}]}
        for line in reversed((proc.stdout or "").splitlines()):
            line = line.strip()
            if line.startswith("{"):
                try:
                    return json.loads(line)
                except ValueError:
                    break
        return {"errors": [{"stage": "subprocess",
                            "trace": (proc.stderr or proc.stdout
                                      or "no output")[-2000:]}]}
    finally:
        if ov_file:
            try:
                Path(ov_file).unlink()
            except OSError:
                pass
