"""Serialize a generated QM config dict into drop-in artifacts for bare QUA.

The State Manager already caches the exact dict ``machine.generate_config()``
produces (``store.generated_config``). Bare-QUA users — who never touch QUAM
``state.json`` / ``wiring.json`` — feed that dict straight to
``QuantumMachinesManager.open_qm``. This module turns the cached dict into two
downloadable files:

* ``config.json`` — the raw config dict, ``json.load``-able as-is.
* ``config.py``   — a standalone module exposing ``config = {...}`` (no QUAM
  import needed), ready to ``from config import config``.

Pure stdlib; NEVER imports the QM stack. The config is always JSON-native here
(it round-tripped through the previewer's ``_result.json``), so ``json.dumps``
cannot fail on it — but we still keep the ``.py`` emission bulletproof for any
string content and any size.
"""

from __future__ import annotations

import json
import pprint
import re

# A pretty ``pprint`` literal is readable + editable, but on a multi-MB config
# (21-qubit chip with arbitrary waveforms) it is slow to build and huge. Above
# this raw-JSON size the ``.py`` embeds the JSON and rehydrates it with
# ``json.loads`` instead — always valid, always fast, regardless of content.
_PY_LITERAL_MAX_BYTES = 1_500_000


def json_bytes(config: dict) -> bytes:
    """The raw config dict as pretty UTF-8 JSON bytes (``json.load``-able)."""
    return json.dumps(config, indent=2, ensure_ascii=False).encode("utf-8")


def safe_stem(chip: str | None) -> str:
    """Filesystem-safe filename stem derived from a chip name."""
    stem = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(chip or "").strip()).strip("_.")
    return stem or "chip"


def _is_finite(config) -> bool:
    """True when the config has no inf/nan. ``pprint`` renders those as the bare
    identifiers ``inf``/``nan`` — NOT valid literals — so a non-finite config
    must take the ``json.loads`` embed branch instead (``json.loads`` parses
    ``Infinity``/``NaN`` back to floats)."""
    try:
        json.dumps(config, allow_nan=False)
        return True
    except ValueError:
        return False


def _header_lines(chip: str | None, meta: dict | None, *, stale: bool) -> list[str]:
    versions = (meta or {}).get("versions") or {}
    at = (meta or {}).get("at")
    # The chip name is a filesystem basename, but it lands raw in a "# ..."
    # comment — collapse any control chars so it can never break out of the
    # comment and inject code (defense in depth).
    chip = re.sub(r"\s+", " ", str(chip)).strip() if chip else None
    lines = [
        f"# QM hardware config for {chip or 'the loaded chip'}"
        " — generated by QUAM State Manager.",
        "#",
        "# This is the exact dict machine.generate_config() produced. Bare QUA needs",
        "# no QUAM state/wiring — feed `config` straight to the OPX:",
        "#",
        "#     from qm import QuantumMachinesManager",
        '#     qmm = QuantumMachinesManager(host="...", cluster_name="...")',
        "#     qm = qmm.open_qm(config)",
        "#     job = qm.execute(my_program)",
        "#",
    ]
    stack = " · ".join(
        f"{k} {versions.get(k)}" for k in ("quam", "quam_builder", "qm") if versions.get(k)
    )
    if at:
        lines.append(f"# Generated {at}" + (f" · {stack}" if stack else "") + ".")
    elif stack:
        lines.append(f"# Source stack: {stack}.")
    if stale:
        lines += [
            "#",
            "# WARNING: this reflects the LAST generated config; the chip's state has",
            "# changed since. Regenerate in the Config Viewer to include recent edits.",
        ]
    return lines


def python_module_source(
    config: dict,
    *,
    chip: str | None = None,
    meta: dict | None = None,
    stale: bool = False,
) -> str:
    """A standalone ``config.py`` module body exposing ``config``.

    Small configs get a readable ``pprint`` literal; large ones embed the JSON
    and rehydrate via ``json.loads`` (bulletproof for any string content —
    quotes, backslashes, ``\"\"\"`` — and fast at any size).
    """
    header = "\n".join(_header_lines(chip, meta, stale=stale))
    raw = json.dumps(config, ensure_ascii=False)

    # The pprint literal is only safe when the config is small AND fully finite:
    # inf/nan would render as bare `inf`/`nan` (exec → NameError). Compare BYTES,
    # not chars, so multi-byte content honours the intended size cap.
    small = len(raw.encode("utf-8")) <= _PY_LITERAL_MAX_BYTES
    if small and _is_finite(config):
        # sort_dicts=False preserves the meaningful config key order
        # (controllers, elements, pulses, …). repr-based, so True/False/None
        # and exact float round-trips — a valid Python literal.
        literal = pprint.pformat(config, indent=1, width=100, sort_dicts=False)
        return f"{header}\n\nconfig = (\n{literal}\n)\n"

    # Large or non-finite: embed via repr() of the JSON string — a
    # guaranteed-valid Python string literal no matter what the config contains,
    # and json.loads() rehydrates Infinity/NaN correctly.
    return f"{header}\n\nimport json\n\nconfig = json.loads({raw!r})\n"
