"""Emit a single, human-editable Python build recipe from a reconstructed spec.

The Re-generate flow rebuilds a chip's *structure* from a spec (see
:mod:`core.regen_spec`) and merges the calibrated values back on
(:mod:`core.regen_merge`). This module produces the third artefact the user
asked to *own*: one standalone ``build_<chip>.py`` that reproduces the same
wiring + design-time seeds as ordinary editable Python — QM's ``generate_*`` and
``populate_*`` template scripts collapsed into a single file.

Design choices:

- **One file** (the user's explicit ask): the wiring block (generate) and the
  populate block live in the same script, run top-to-bottom.
- **Public idiom only** — ``qualang_tools.wirer`` + ``quam_builder`` +
  ``from quam_config import Quam`` + (for pairs) the template's ``pair_gates``.
  Exactly the imports QM's own template scripts use, so the file drops into a
  calibration repo's ``quam_config/`` folder and runs. The State Manager process
  never imports these; this module only emits *text*.
- **Pinned ports** — each line carries the source chip's exact
  ``mw_fem_spec`` / ``lf_fem_spec`` constraint, so an untouched chip rebuilds to
  the identical wiring; edit the constraint to move a port.
- **Recipe, not snapshot** — measured calibration (T1/T2, fitted gate amps,
  extra pulse variants) is NOT emitted; it lives in the merged ``state.json``.
  The header says so plainly. This script rebuilds structure + seeds.

Pure string generation over the plain spec dict — no ``quam`` imports, fully
unit-testable (the emitted source is ``compile()``-checked in tests). See
``docs/51_regenerate_config.md``.
"""

from __future__ import annotations

from typing import Any

# gate family (spec ``pair_gate`` / per-pair) -> the string the template's
# ``pair_gates.add_pair_gate`` expects. Fixed + tunable both seed a "CZ".
_GATE_STR = {"cz_tunable": "CZ", "cz_fixed": "CZ", "cr": "CR"}


def _norm_index(qubit_id: Any) -> str:
    """Mirror ``run_build._norm_index`` — strip the leading ``q``/``Q`` so the
    wiring index matches what ``QubitReference`` re-adds (avoids ``qqA1``)."""
    s = str(qubit_id)
    if s[:1] in ("q", "Q"):
        s = s[1:]
    return s


def _fmt(v: Any) -> str:
    """Python literal for a spec scalar, preserving float precision via repr."""
    if isinstance(v, bool) or v is None:
        return repr(v)
    if isinstance(v, float):
        return repr(v)
    return repr(v)


def _mw(ch: dict) -> str:
    parts = [f"con={ch.get('con')}", f"slot={ch.get('slot')}"]
    if ch.get("in_port") is not None:
        parts.append(f"in_port={ch['in_port']}")
    if ch.get("out_port") is not None:
        parts.append(f"out_port={ch['out_port']}")
    return "mw_fem_spec(" + ", ".join(parts) + ")"


def _lf(ch: dict) -> str:
    slot = ch.get("out_slot", ch.get("slot"))
    parts = [f"con={ch.get('con')}", f"out_slot={slot}", f"out_port={ch.get('out_port')}"]
    return "lf_fem_spec(" + ", ".join(parts) + ")"


def _dict_block(name: str, d: dict) -> str:
    """Render ``NAME = { 'qA1': {...}, ... }`` one entity per line, stable order."""
    if not d:
        return f"{name} = {{}}\n"
    lines = [f"{name} = {{"]
    for k in d:
        inner = ", ".join(f"{_fmt(ik)}: {_fmt(iv)}" for ik, iv in d[k].items())
        lines.append(f"    {_fmt(k)}: {{{inner}}},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def emit_build_script(spec: dict, chip_name: str | None = None) -> str:
    """Return the source of a standalone ``build_<chip>.py`` for ``spec``.

    ``spec`` is a :func:`core.regen_spec.reconstruct_spec` spec (network,
    instruments, qubits, qubit_pairs, lines, pair_gate, populate). The emitted
    file rebuilds wiring + seeds; calibration comes from the merged state.json.
    """
    net = spec.get("network", {}) or {}
    instruments = spec.get("instruments", {}) or {}
    lines = spec.get("lines", []) or []
    populate = spec.get("populate", {}) or {}
    default_gate = spec.get("pair_gate", "cz_fixed")
    chip = chip_name or "chip"

    out: list[str] = []
    w = out.append

    # ---- header --------------------------------------------------------------
    w('#!/usr/bin/env python')
    w('"""Build recipe for %s — generated by QUAM State Manager (Re-generate Config).' % chip)
    w('')
    w('ONE editable script = the QM generate + populate steps combined. Edit the')
    w('data blocks (network / instruments / wiring / populate / PAIRS) and re-run')
    w('to rebuild state.json + wiring.json:')
    w('')
    w('    python %s [STATE_DIR]' % f"build_{chip}.py")
    w('')
    w('Run it inside your calibration repo (needs `quam`, `quam_builder`,')
    w('`qualang_tools`, a local `quam_config.Quam`, and — for the pairs step —')
    w("the template's `pair_gates.py`), same context as QM's own generate_*/")
    w('populate_* scripts.')
    w('')
    w('NOTE: measured calibration (T1/T2, fitted gate amplitudes, extra pulse')
    w('variants) is NOT in this recipe — it lives in the state.json the State')
    w('Manager merged. This rebuilds the STRUCTURE + design-time seeds only.')
    w('"""')
    w('import os')
    w('import sys')
    w('')
    w('if len(sys.argv) > 1 and not sys.argv[1].startswith("--"):')
    w('    os.environ["QUAM_STATE_PATH"] = sys.argv[1]')
    w('')
    w('import numpy as np  # noqa: F401  (kept for hand-edited value arrays)')
    w('from qualang_tools.wirer import Connectivity, Instruments, allocate_wiring')
    w('from qualang_tools.wirer.wirer.channel_specs import mw_fem_spec, lf_fem_spec')
    w('from qualang_tools.units import unit')
    w('from quam_builder.builder.qop_connectivity import build_quam_wiring')
    w('from quam_builder.builder.superconducting import build_quam')
    w('from quam_config import Quam')
    w('')
    w('u = unit(coerce_to_integer=True)')
    w('')

    # ---- network -------------------------------------------------------------
    w('# ============================ EDIT: network ============================')
    w('HOST = %s' % _fmt(net.get("host")))
    w('CLUSTER = %s' % _fmt(net.get("cluster_name")))
    w('PORT = %s' % _fmt(net.get("port")))
    w('')

    # ---- instruments ---------------------------------------------------------
    w('# ========================== EDIT: instruments =========================')
    w('instruments = Instruments()')
    for ctrl in instruments.get("controllers", []):
        con = ctrl.get("con")
        mw_slots = sorted(f["slot"] for f in ctrl.get("fems", []) if f.get("fem") == "mw")
        lf_slots = sorted(f["slot"] for f in ctrl.get("fems", []) if f.get("fem") == "lf")
        if mw_slots:
            w('instruments.add_mw_fem(controller=%r, slots=%r)' % (con, mw_slots))
        if lf_slots:
            w('instruments.add_lf_fem(controller=%r, slots=%r)' % (con, lf_slots))
    w('')

    # ---- wiring --------------------------------------------------------------
    w('# ============================= EDIT: wiring ===========================')
    w('# Ports are PINNED from the source chip — edit a constraint to move a port.')
    w('connectivity = Connectivity()')
    w('')
    # resonator groups (multiplexed feed-lines)
    res_groups: dict[str, list[dict]] = {}
    for ln in lines:
        if ln.get("line") == "resonator":
            g = ln.get("group", "__solo__" + str(ln.get("element")))
            res_groups.setdefault(g, []).append(ln)
    if res_groups:
        w('# readout feed-lines (multiplexed: qubits sharing one MW in/out port)')
        for items in res_groups.values():
            qs = [_norm_index(it["element"]) for it in items]
            ch = items[0].get("channel", {})
            w('connectivity.add_resonator_line(qubits=%r, constraints=%s)' % (qs, _mw(ch)))
        w('allocate_wiring(connectivity, instruments, block_used_channels=True)')
        w('')
    # drive
    drive = [ln for ln in lines if ln.get("line") == "drive"]
    if drive:
        w('# xy drive')
        for ln in drive:
            w('connectivity.add_qubit_drive_lines(qubits=%r, constraints=%s)'
              % (_norm_index(ln["element"]), _mw(ln.get("channel", {}))))
        w('allocate_wiring(connectivity, instruments, block_used_channels=True)')
        w('')
    # flux
    flux = [ln for ln in lines if ln.get("line") == "flux"]
    if flux:
        w('# qubit flux (z)')
        for ln in flux:
            w('connectivity.add_qubit_flux_lines(qubits=%r, constraints=%s)'
              % (_norm_index(ln["element"]), _lf(ln.get("channel", {}))))
        w('allocate_wiring(connectivity, instruments, block_used_channels=True)')
        w('')
    # coupler (tunable-coupler chips only)
    coupler = [ln for ln in lines if ln.get("line") == "coupler"]
    if coupler:
        w('# tunable-coupler flux')
        for ln in coupler:
            c, t = str(ln["element"]).split("-", 1)
            w('connectivity.add_qubit_pair_flux_lines(qubit_pairs=[(%r, %r)], constraints=%s)'
              % (_norm_index(c), _norm_index(t), _lf(ln.get("channel", {}))))
        w('allocate_wiring(connectivity, instruments, block_used_channels=True)')
        w('')
    # readout TWPA pumps (modern quam_builder seeds pump + pump_ on the given port)
    twpa_pumps = [ln for ln in lines if ln.get("line") == "twpa_pump"]
    twpa_iso = {ln["element"]: ln.get("channel") for ln in lines if ln.get("line") == "twpa_isolation"}
    if twpa_pumps:
        w('# readout TWPA pumps (add_twpa_lines seeds pump + pump_ on the port)')
        for ln in twpa_pumps:
            tid = ln["element"]
            args = "twpas=[%r], pump_constraints=%s" % (tid, _mw(ln.get("channel", {})))
            if twpa_iso.get(tid):
                args += ", isolation_constraints=%s" % _mw(twpa_iso[tid])
            w('connectivity.add_twpa_lines(%s)' % args)
        w('allocate_wiring(connectivity, instruments)')
        w('')

    # ---- build ---------------------------------------------------------------
    w('# =============================== build ================================')
    w('machine = Quam()')
    w('build_quam_wiring(connectivity, HOST, CLUSTER, machine)')
    w('machine = Quam.load()')
    w('build_quam(machine)')
    w('print(f"wiring built: {len(machine.qubits)} qubits, {len(machine.qubit_pairs)} pairs")')
    w('')

    # ---- populate data blocks ------------------------------------------------
    w('# ============================ EDIT: populate ==========================')
    w('# design-time seeds (RF/LO/anharmonicity/grid, readout, flux, 1Q pulses).')
    w(_dict_block("QUBIT", populate.get("qubit", {})).rstrip("\n"))
    w('')
    w(_dict_block("RESONATOR", populate.get("resonator", {})).rstrip("\n"))
    w('')
    w(_dict_block("FLUX", populate.get("flux", {})).rstrip("\n"))
    w('')
    w(_dict_block("PULSES", populate.get("pulses", {})).rstrip("\n"))
    w('')

    # per-pair gate family map (id -> "CZ"/"CR")
    pair_gate_map: dict[str, str] = {}
    for pair in spec.get("qubit_pairs", []) or []:
        if isinstance(pair, (list, tuple)) and len(pair) == 2:
            pid = "%s-%s" % (pair[0], pair[1])
            pair_gate_map[pid] = _GATE_STR.get(default_gate, "CZ")
    w(_pairs_block(pair_gate_map))
    w('DEFAULT_PAIR_GATE = %r  # applied to any pair not listed in PAIRS' % _GATE_STR.get(default_gate, "CZ"))
    w('')

    # ---- populate loops ------------------------------------------------------
    w('def get_band(freq):')
    w('    if 50e6 <= freq < 5.5e9:')
    w('        return 1')
    w('    if 4.5e9 <= freq < 7.5e9:')
    w('        return 2')
    w('    if 6.5e9 <= freq <= 10.5e9:')
    w('        return 3')
    w('    raise ValueError(f"{freq} Hz outside any MW-FEM band")')
    w('')
    w('try:')
    w('    from quam_builder.builder.superconducting.pulses import add_DragCosine_pulses')
    w('except ImportError:  # newer quam_builder moved it')
    w('    from quam_builder.builder.superconducting.add_default_pulses import add_DragCosine_pulses')
    w('')
    w('for qid, q in machine.qubits.items():')
    w('    v = QUBIT.get(qid, {})')
    w('    if "RF_freq" in v:')
    w('        q.f_01 = float(v["RF_freq"]); q.xy.RF_frequency = float(v["RF_freq"])')
    w('    if "LO_frequency" in v:')
    w('        lo = float(v["LO_frequency"])')
    w('        q.xy.opx_output.upconverter_frequency = lo')
    w('        # real band from the source chip; get_band(lo) only as a fallback')
    w('        q.xy.opx_output.band = v.get("band", get_band(lo))')
    w('    if "full_scale_power_dbm" in v:')
    w('        q.xy.opx_output.full_scale_power_dbm = v["full_scale_power_dbm"]')
    w('    if "anharmonicity" in v:')
    w('        q.anharmonicity = float(v["anharmonicity"])')
    w('    if "grid_location" in v:')
    w('        q.grid_location = v["grid_location"]')
    w('')
    w('    r = RESONATOR.get(qid, {})')
    w('    if r and getattr(q, "resonator", None) is not None:')
    w('        rr = q.resonator')
    w('        if "RF_freq" in r:')
    w('            rr.f_01 = float(r["RF_freq"]); rr.RF_frequency = float(r["RF_freq"])')
    w('        if "LO_frequency" in r:')
    w('            rr.opx_output.upconverter_frequency = float(r["LO_frequency"])')
    w('            _rb = r.get("band", get_band(float(r["LO_frequency"])))')
    w('            rr.opx_output.band = _rb; rr.opx_input.band = _rb')
    w('        if "full_scale_power_dbm" in r:')
    w('            rr.opx_output.full_scale_power_dbm = r["full_scale_power_dbm"]')
    w('        for _k in ("depletion_time", "time_of_flight"):')
    w('            if _k in r:')
    w('                setattr(rr, _k, r[_k])')
    w('        if "readout_length" in r:')
    w('            rr.operations["readout"].length = r["readout_length"]')
    w('        if "readout_amplitude" in r:')
    w('            rr.operations["readout"].amplitude = r["readout_amplitude"]')
    w('')
    w('    f = FLUX.get(qid, {})')
    w('    if f and getattr(q, "z", None) is not None:')
    w('        for _k in ("independent_offset", "joint_offset", "min_offset",')
    w('                   "arbitrary_offset", "flux_point", "settle_time"):')
    w('            if _k in f:')
    w('                setattr(q.z, _k, f[_k])')
    w('        for _k in ("output_mode", "upsampling_mode"):')
    w('            if _k in f:')
    w('                setattr(q.z.opx_output, _k, f[_k])')
    w('')
    w('    p = PULSES.get(qid, {})')
    w('    if p:')
    w('        add_DragCosine_pulses(')
    w('            q, amplitude=p.get("x180_amplitude", 0.1),')
    w('            length=p.get("x180_length", 40),')
    w('            anharmonicity=q.get_reference() + "/anharmonicity",')
    w('            alpha=p.get("drag_alpha", 0.0), detuning=p.get("drag_detuning", 0))')
    w('        if "saturation_length" in p:')
    w('            q.xy.operations["saturation"].length = p["saturation_length"]')
    w('        if "saturation_amplitude" in p:')
    w('            q.xy.operations["saturation"].amplitude = p["saturation_amplitude"]')
    w('')
    # pairs
    w('# ---- two-qubit gates: uses the template pair_gates helper --------------')
    w('# Two paths, chosen at runtime by whether build_quam already made the pairs:')
    w('#   tunable coupler -> pairs exist from the coupler wiring; park each coupler')
    w('#                      off + amplified, then add_gates(..., coupler=pair.coupler).')
    w('#   fixed coupler/CR -> no coupler wiring; add_pair_gate(c, t, ...) creates them.')
    w('if PAIRS or machine.qubit_pairs:')
    w('    try:                              # run from inside quam_config/ ...')
    w('        import pair_gates as pg')
    w('    except ImportError:               # ... or quam_config installed as a pkg')
    w('        from quam_config import pair_gates as pg')
    w('    if machine.qubit_pairs:           # tunable coupler: pairs already wired')
    w('        for pid, pair in machine.qubit_pairs.items():')
    w('            cpl = getattr(pair, "coupler", None)')
    w('            if cpl is not None:       # park the coupler "off" (calibrate later)')
    w('                cpl.flux_point = "off"; cpl.decouple_offset = 0.0')
    w('                cpl.opx_output.output_mode = "amplified"')
    w('                cpl.opx_output.upsampling_mode = "pulse"')
    w('            gate = PAIRS.get(pid, DEFAULT_PAIR_GATE)')
    w('            pg.add_gates(machine, pair, gate, coupler=cpl)')
    w('            print(f"  {pid}: {gate} -> {list(pair.macros.keys())}")')
    w('    else:                             # fixed coupler / CR: create the pairs')
    w('        for pid, gate in PAIRS.items():')
    w('            c, t = pid.split("-", 1)')
    w('            pair = pg.add_pair_gate(machine, c, t, gate, coupler=None)')
    w('            print(f"  {pid}: {gate} -> {list(pair.macros.keys())}")')
    w('')
    w('machine.save()')
    w('cfg = machine.generate_config()')
    w('print(f"saved + generate_config() OK: {len(cfg[\'elements\'])} elements")')
    w('')

    return "\n".join(out)


def _pairs_block(pair_gate_map: dict[str, str]) -> str:
    if not pair_gate_map:
        return "PAIRS = {}  # gate family per pair, e.g. 'CZ' | 'CR'"
    lines = ["PAIRS = {  # gate family per pair — edit to 'CZ' | 'CR'"]
    for pid, gate in pair_gate_map.items():
        lines.append("    %r: %r," % (pid, gate))
    lines.append("}")
    return "\n".join(lines)
