#!/usr/bin/env python
"""demo — step 1/3: instruments, wiring + base machine.

Generated by QUAM State Manager (2026-01-01). Edit the data blocks and re-run:

    python 01_make_wiring.py [STATE_DIR]      # default ./quam_state

Lines are added in the SAME order the wizard used and allocated in one
pass, so the allocator lands on the wizard's exact ports (each line's
allocated port is noted in a comment — pin it via `constraints=` to
survive re-ordering). Point STATE_DIR at an EMPTY folder: quam loads
every .json under it, so stray files corrupt the build.
"""
import os
import sys
import inspect

STATE_DIR = sys.argv[1] if len(sys.argv) > 1 else "./quam_state"
os.makedirs(STATE_DIR, exist_ok=True)
_stray = [f for f in os.listdir(STATE_DIR) if f.endswith('.json')
          and f not in ('state.json', 'wiring.json')]
if _stray:
    sys.exit(f'STATE_DIR contains stray JSON files {_stray} — quam would '
             'recursively load them. Use an empty folder.')
os.environ["QUAM_STATE_PATH"] = os.path.abspath(STATE_DIR)

from qualang_tools.wirer import Connectivity, Instruments, allocate_wiring
from qualang_tools.wirer.wirer.channel_specs import (  # noqa: F401
    mw_fem_spec, lf_fem_spec, opx_spec, octave_spec,
)
from quam_builder.builder.qop_connectivity import build_quam_wiring
from quam_builder.builder.superconducting import build_quam
from quam_builder.architecture.superconducting.qpu import (FluxTunableQuam as QuamCls)

# ============================ EDIT: network ============================
HOST = '10.1.1.1'
CLUSTER = 'CL'
PORT = None

# ========================== EDIT: instruments =========================
instruments = Instruments()
instruments.add_mw_fem(controller=1, slots=[1])
instruments.add_lf_fem(controller=1, slots=[2])

# ============================= EDIT: wiring ===========================
# SAME insertion order as the wizard (this is what reproduces its ports).
connectivity = Connectivity()

# readout feed-lines (multiplexed: qubits sharing one MW in/out port)
connectivity.add_resonator_line(qubits=[1, 2], constraints=mw_fem_spec(in_port=1, out_port=8))  # allocated: con1 s1 p8 (output), con1 s1 p1 (input)

connectivity.add_qubit_drive_lines(qubits=1, constraints=None)  # allocated: con1 s1 p2 (output)
connectivity.add_qubit_drive_lines(qubits=2, constraints=None)
connectivity.add_qubit_flux_lines(qubits=1, constraints=None)
connectivity.add_qubit_flux_lines(qubits=2, constraints=None)
connectivity.add_qubit_pair_flux_lines(qubit_pairs=[(1, 2)], constraints=None)  # allocated: con1 s2 p5 (output)

allocate_wiring(connectivity, instruments)

# =============================== build ================================
machine = QuamCls()
# Older quam_builder takes an explicit path kwarg; newer reads
# QUAM_STATE_PATH — the same shim the wizard build uses.
_kwargs = {"port": PORT}
if "path" in inspect.signature(build_quam_wiring).parameters:
    _kwargs["path"] = os.environ["QUAM_STATE_PATH"]
build_quam_wiring(connectivity, HOST, CLUSTER, machine, **_kwargs)
machine = QuamCls.load()
build_quam(machine)
print(f"wiring built: {len(machine.qubits)} qubits, "
      f"{len(machine.qubit_pairs)} pairs -> {os.environ['QUAM_STATE_PATH']}")
