#!/usr/bin/env python
"""demo — step 2/3: populate physics values + 2Q gates, then save.

Generated by QUAM State Manager (2026-01-01). Run AFTER 01_make_wiring.py,
same STATE_DIR:

    python 02_build_machine.py [STATE_DIR]   # default ./quam_state

Edit the DATA blocks (POPULATE / QUBIT_PAIRS / PAIR_GATE) and re-run 01
then 02 to rebuild. The machinery below the data is copied verbatim from
the State Manager's own build subprocess — including the readout-LO
pointer fix-up — so this bundle reproduces state.json byte-for-byte.
"""
import json
import os
import sys
from pathlib import Path

STATE_DIR = sys.argv[1] if len(sys.argv) > 1 else "./quam_state"
os.environ["QUAM_STATE_PATH"] = os.path.abspath(STATE_DIR)

from quam_builder.architecture.superconducting.qpu import (FluxTunableQuam as QuamCls)

# ============================ EDIT: populate ==========================
# Base SI units (Hz, ns, V, dimensionless amp). Blank/missing keys keep
# quam_builder defaults (x180: amp 0.1 / len 40 ns; anharmonicity -200e6).
POPULATE = {   'pairs': {'q1-q2': {'cz_amplitude': 0.1, 'cz_variant': 'unipolar'}},
    'pulses': {'q1': {'x180_amplitude': 0.12, 'x180_length': 48}},
    'qubit': {'q1': {'RF_freq': 5200000000.0}, 'q2': {'RF_freq': 4900000000.0}}}

# [control, target] per pair — for CZ chips the wizard ordered these
# control = higher-f qubit; the flux pulse plays on the moving qubit.
QUBIT_PAIRS = [['q1', 'q2']]

# 2Q-gate family: 'cz_tunable' | 'cz_fixed' | 'cr' | '' (no wizard gate).
PAIR_GATE = 'cz_tunable'

# CR drive port mode: '' | 'dedicated' | 'shared_xy' (the customer's
# dual-upconverter layout — CR/ZZ ride the control's xy port, LO 2).
CR_PORT_MODE = ''
PAIR_LINES = []

# ======================================================================
# Machinery — VERBATIM from the State Manager's generator/run_build.py
# (the exact code the wizard ran to build this chip). Edit the DATA
# blocks above instead; change these only if you know the QUAM stack.
# ======================================================================

_BAND_TO_DELAY_NS = {1: 141, 2: 161, 3: 141}
_CZ_VARIANTS = ('unipolar', 'flattop', 'bipolar', 'SNZ', 'flattop_erf')
_PULSE_HOMES = ('quam.components.pulses', 'quam_builder.architecture.superconducting.components.pulses', 'quam_builder.common.pulses')

def _norm_index(qubit_id):
    """Normalise a spec qubit id to the index QubitReference expects.

    ``"q1"`` -> ``1``; ``"qA1"`` -> ``"A1"``; ``1`` -> ``1``; ``"A1"`` -> ``"A1"``.
    QM's ``QubitReference(index)`` renders as ``f"q{index}"``, so the leading
    ``q`` must be stripped to avoid a doubled ``qq1``.
    """
    s = str(qubit_id)
    if s[:1] in ("q", "Q"):
        s = s[1:]
    return int(s) if s.isdigit() else s

def _parse_pair(pair_id):
    """Split a spec qubit-pair id into ``(control_index, target_index)``.

    ``"q1-q2"`` -> ``(1, 2)``; ``"qA1-qB2"`` -> ``("A1", "B2")``. Splits on the
    first ``-`` so multi-character qubit labels survive.
    """
    parts = str(pair_id).split("-", 1)
    if len(parts) != 2:
        raise ValueError(f"invalid qubit-pair id: {pair_id!r}")
    return _norm_index(parts[0]), _norm_index(parts[1])

def _quam_pair_id(spec_pair_id):
    """Map a spec pair id ('q1-q2') to QUAM's qubit_pair key ('q1-2')."""
    control, target = _parse_pair(spec_pair_id)
    return "q" + str(control) + "-" + str(target)

def _norm_pair_qubits(spec_pair):
    """``["q1","q2"]`` -> ``("q1", "q2", "q1-2")`` (control, target, QUAM pair id)."""
    if not (isinstance(spec_pair, (list, tuple)) and len(spec_pair) == 2):
        return None
    control, target = str(spec_pair[0]), str(spec_pair[1])
    if not control or not target:
        return None
    return control, target, _quam_pair_id(f"{control}-{target}")

def _num(v):
    """Return ``v`` if it is a real finite number, else None (rejects bool, str,
    None, and unresolved JSON-pointer strings)."""
    if isinstance(v, bool):
        return None
    if isinstance(v, (int, float)):
        return v
    return None

def _target_lo(qubit):
    """The target qubit's xy LO frequency for a CR drive — the port's literal
    ``upconverter_frequency`` (mirrors the customer ``add_cr``), falling back to a
    numeric ``xy.LO_frequency``. None when neither resolves to a number."""
    xy = getattr(qubit, "xy", None)
    if xy is None:
        return None
    port = getattr(xy, "opx_output", None)
    lo = _num(getattr(port, "upconverter_frequency", None)) if port is not None else None
    if lo is None:
        lo = _num(getattr(xy, "LO_frequency", None))
    return lo

def _band_for(freq):
    """MW-FEM Nyquist band (1/2/3) for an up/down-converter frequency in Hz."""
    if not isinstance(freq, (int, float)):
        return None
    if 50e6 <= freq < 5.5e9:
        return 1
    if 4.5e9 <= freq < 7.5e9:
        return 2
    if 6.5e9 <= freq <= 10.5e9:
        return 3
    return None

def _delay_for_band(band):
    """LF-FEM delay (ns) for an MW-FEM band, or ``None`` if unknown."""
    return _BAND_TO_DELAY_NS.get(band)

def _apply_lf_delay(lf_port, band):
    """Set ``lf_port.delay`` based on the MW-FEM ``band`` it should align with.

    Safe no-op if *lf_port* is None, doesn't carry a ``delay`` attribute, or
    *band* is not one of {1, 2, 3}.
    """
    if lf_port is None or not hasattr(lf_port, "delay"):
        return
    ns = _delay_for_band(band)
    if ns is None:
        return
    try:
        lf_port.delay = ns
    except (ValueError, TypeError):
        # QUAM may raise on reference-assignment paths; silently skip.
        pass

def _set_port_lo(port, lo, band):
    if port is None:
        return
    # An input port's downconverter_frequency / band are usually QUAM
    # references to the coupled output port — assigning the output value
    # propagates automatically. QUAM raises ValueError on assigning over a
    # reference, so those attributes are simply skipped.
    for attr in ("upconverter_frequency", "downconverter_frequency"):
        if hasattr(port, attr):
            try:
                setattr(port, attr, lo)
            except ValueError:
                pass
    if band is not None and hasattr(port, "band"):
        try:
            port.band = band
        except ValueError:
            pass

def _set_channel_lo(channel, lo):
    """Set a channel's up/down-converter LO and the matching MW-FEM band.

    MW-FEM channels carry the LO on their ports; IQ channels carry it on the
    channel's ``LO_frequency``.
    """
    band = _band_for(lo)
    out = getattr(channel, "opx_output", None)
    if out is not None and hasattr(out, "upconverter_frequency"):
        _set_port_lo(out, lo, band)
        _set_port_lo(getattr(channel, "opx_input", None), lo, band)
    elif hasattr(channel, "LO_frequency"):
        channel.LO_frequency = lo

def _operation(channel, name):
    """Return a named operation/pulse on a channel, or None."""
    ops = getattr(channel, "operations", None)
    if ops is not None and name in ops:
        return ops[name]
    return None

def _apply_resonator(resonator, vals):
    if "RF_freq" in vals:
        resonator.f_01 = vals["RF_freq"]
        resonator.RF_frequency = vals["RF_freq"]
    if "LO_frequency" in vals:
        _set_channel_lo(resonator, vals["LO_frequency"])
    if "depletion_time" in vals:
        resonator.depletion_time = vals["depletion_time"]
    if "time_of_flight" in vals:
        resonator.time_of_flight = vals["time_of_flight"]
    # Readout MW-FEM port full-scale power. Multiplexed feedlines share a
    # single port, so writing the same value across the feedline group from
    # the UI lands on the same MWFEMAnalogOutputPort here.
    if "full_scale_power_dbm" in vals:
        out = getattr(resonator, "opx_output", None)
        if out is not None and hasattr(out, "full_scale_power_dbm"):
            out.full_scale_power_dbm = vals["full_scale_power_dbm"]
    readout = _operation(resonator, "readout")
    if readout is not None:
        if "readout_length" in vals:
            readout.length = vals["readout_length"]
        if "readout_amplitude" in vals:
            readout.amplitude = vals["readout_amplitude"]

def _apply_qubit(qubit, vals):
    if "RF_freq" in vals:
        qubit.f_01 = vals["RF_freq"]
        if getattr(qubit, "xy", None) is not None:
            qubit.xy.RF_frequency = vals["RF_freq"]
    if "anharmonicity" in vals:
        qubit.anharmonicity = vals["anharmonicity"]
    if "grid_location" in vals:
        qubit.grid_location = vals["grid_location"]

    xy = getattr(qubit, "xy", None)
    if xy is not None:
        if "LO_frequency" in vals:
            _set_channel_lo(xy, vals["LO_frequency"])
        if "full_scale_power_dbm" in vals:
            out = getattr(xy, "opx_output", None)
            if out is not None and hasattr(out, "full_scale_power_dbm"):
                out.full_scale_power_dbm = vals["full_scale_power_dbm"]

    # Align the LF-FEM z output with the MW-FEM xy band so flux pulses arrive
    # at the chip simultaneously with the MW drive. Editable per-port from the
    # qubit detail page after generation. See docs/31_lf_fem_delay.md.
    z = getattr(qubit, "z", None)
    if z is not None:
        z_port = getattr(z, "opx_output", None)
        xy_port = getattr(xy, "opx_output", None) if xy is not None else None
        band = getattr(xy_port, "band", None)
        _apply_lf_delay(z_port, band)

def _apply_flux(flux_line, vals):
    for attr in ("independent_offset", "joint_offset", "min_offset",
                 "arbitrary_offset", "flux_point", "settle_time"):
        if attr in vals:
            setattr(flux_line, attr, vals[attr])
    out = getattr(flux_line, "opx_output", None)
    if out is not None:
        for attr in ("output_mode", "upsampling_mode"):
            if attr in vals and hasattr(out, attr):
                setattr(out, attr, vals[attr])

def _apply_pulses(machine, vals):
    """Add the single-qubit DragCosine gate set and tune the saturation pulse.

    ``vals`` is now per-qubit: ``{qid: {x180_length, x180_amplitude, drag_alpha,
    drag_detuning, saturation_length, saturation_amplitude}}``. Real device
    states show per-qubit calibration (e.g. LabA' eight distinct DRAG α
    values across nine qubits), so the wizard stores per-qubit values; an
    empty per-qubit override falls back to QUAM defaults
    (x180_length=40, x180_amplitude=0.1, alpha=0, detuning=0). The wizard's
    "Set all →" row writes the same value to every qubit, which is the new
    way to express a global default.

    build_quam only adds a `saturation` pulse — the x180/x90/y… gates come
    from add_DragCosine_pulses (as in QM's own populate_quam_*.py). They are
    added unconditionally so every generated config is usable.
    """
    # add_DragCosine_pulses lived in `.pulses` in older quam_builder versions
    # and moved into `.add_default_pulses` later. Try both so the generator
    # works across the versions teams have pinned.
    try:
        from quam_builder.builder.superconducting.pulses import add_DragCosine_pulses
    except ModuleNotFoundError:
        from quam_builder.builder.superconducting.add_default_pulses import (
            add_DragCosine_pulses,
        )

    qubits = getattr(machine, "qubits", None) or {}
    for qid, qubit in qubits.items():
        if getattr(qubit, "xy", None) is None:
            continue
        q_vals = (vals or {}).get(qid) or {}
        # add_DragCosine_pulses references the qubit's `anharmonicity` attribute
        # (`#.../anharmonicity`). build_quam leaves it None and the populate step
        # is OPTIONAL, so a chip generated without an anharmonicity value would
        # make generate_config() crash the moment it builds the DRAG Q-component
        # (`derivative * (alpha / anharmonicity)` → `float * None` TypeError).
        # Default it to a standard transmon value so the zero-populate path still
        # yields a usable config; any value already set by _apply_qubit (from the
        # populate block) is preserved, and the user can edit it afterwards.
        if getattr(qubit, "anharmonicity", None) is None:
            qubit.anharmonicity = -200e6
        add_DragCosine_pulses(
            qubit,
            amplitude=q_vals.get("x180_amplitude", 0.1),
            length=q_vals.get("x180_length", 40),
            anharmonicity=qubit.get_reference() + "/anharmonicity",
            alpha=q_vals.get("drag_alpha", 0.0),
            detuning=q_vals.get("drag_detuning", 0),
        )
        saturation = _operation(qubit.xy, "saturation")
        if saturation is not None:
            if "saturation_length" in q_vals:
                saturation.length = q_vals["saturation_length"]
            if "saturation_amplitude" in q_vals:
                saturation.amplitude = q_vals["saturation_amplitude"]

def _make_cz_gate(cz_gate_cls, pulse_id, moving):
    """Construct a CZGate with ``moving_qubit`` only when the class accepts it.

    Older quam_builder versions exposed CZGate(flux_pulse_qubit=..., moving_qubit=...);
    newer ones drop ``moving_qubit`` and instead read it off the pair object
    (which we already set via ``pair.moving_qubit = moving``).
    """
    import inspect

    if "moving_qubit" in inspect.signature(cz_gate_cls.__init__).parameters:
        return cz_gate_cls(flux_pulse_qubit=pulse_id, moving_qubit=moving)
    return cz_gate_cls(flux_pulse_qubit=pulse_id)

def _apply_pairs(machine, pairs_vals):
    """Add the requested gate macro to each qubit pair and tune the coupler.

    build_quam leaves `qubit_pair.macros` empty. The flux pulse goes on the
    *moving* qubit's z line — `moving_qubit` (``control`` or ``target``,
    user-settable, default ``control``) picks which one — and the gate
    macro references the pulse by name.

    Spec dispatch via ``gate_type`` (default ``cz_unipolar`` for backwards
    compat):

    - ``cz_unipolar``: DC flux pulse via :class:`CZGate`. Fields:
      ``cz_amplitude``, ``cz_interaction_duration``.
    - ``cz_parametric``: AC-flux modulated CZ via :class:`ParametricCZGate`.
      Fields: ``cz_amplitude``, ``cz_interaction_duration``, and
      ``cz_modulation_frequency`` (Hz, default 0). Requires quam_builder
      with ParametricCZGate exported.
    """
    from quam.components.pulses import SquarePulse
    from quam_builder.architecture.superconducting.custom_gates.flux_tunable_transmon_pair.two_qubit_gates import (
        CZGate,
    )

    qpairs = getattr(machine, "qubit_pairs", None) or {}
    for spec_id, vals in pairs_vals.items():
        quam_id = _quam_pair_id(spec_id)
        if quam_id not in qpairs:
            continue
        pair = qpairs[quam_id]
        duration = vals.get("cz_interaction_duration", 100)
        amplitude = vals.get("cz_amplitude", 0.1)
        gate_type = vals.get("gate_type", "cz_unipolar")

        moving = vals.get("moving_qubit")
        if moving not in ("control", "target"):
            moving = "control"
        pair.moving_qubit = moving
        moving_q = getattr(
            pair, "qubit_control" if moving == "control" else "qubit_target", None
        )

        if moving_q is not None and getattr(moving_q, "z", None) is not None:
            pulse_id = "cz_" + quam_id.replace("-", "_") + "_pulse"
            moving_q.z.operations[pulse_id] = SquarePulse(
                length=duration, amplitude=amplitude
            )
            if gate_type == "cz_parametric":
                # Lazy import so installations without the upgraded
                # quam_builder still load the rest of the generator.
                try:
                    from quam_builder.architecture.superconducting.custom_gates.flux_tunable_transmon_pair.two_qubit_gates import (
                        ParametricCZGate,
                    )
                except ImportError:
                    print(
                        f"WARNING: pair {quam_id}: gate_type='cz_parametric' requested "
                        "but ParametricCZGate is not available in this quam_builder "
                        "install — falling back to cz_unipolar.",
                        file=sys.stderr,
                    )
                    pair.macros["cz_unipolar"] = _make_cz_gate(CZGate, pulse_id, moving)
                else:
                    mod_freq = vals.get("cz_modulation_frequency", 0.0)
                    pair.macros["cz_parametric"] = ParametricCZGate(
                        flux_pulse_qubit=pulse_id,
                        modulation_frequency=float(mod_freq),
                    )
            else:
                pair.macros["cz_unipolar"] = _make_cz_gate(CZGate, pulse_id, moving)

        coupler = getattr(pair, "coupler", None)
        if coupler is not None:
            for attr in ("decouple_offset", "interaction_offset",
                         "flux_point", "settle_time"):
                key = "coupler_" + attr
                if key in vals:
                    setattr(coupler, attr, vals[key])

            # Align the LF-FEM coupler delay with the moving qubit's xy band:
            # during a 2Q gate the coupler plays at the same time as the
            # moving qubit's MW drive, so they must share the same delay.
            moving_xy_port = (
                getattr(getattr(moving_q, "xy", None), "opx_output", None)
                if moving_q is not None else None
            )
            coupler_band = getattr(moving_xy_port, "band", None)
            _apply_lf_delay(getattr(coupler, "opx_output", None), coupler_band)

def apply_populate(machine, populate, handle_pairs=True):
    """Apply spec['populate'] physics values onto a built QUAM machine.

    When *handle_pairs* is False the caller owns pair-gate creation (the wizard
    path drives it from ``spec['pair_gate']`` via :func:`_finalize_pair_gates`),
    so the legacy ``populate['pairs']`` path is skipped to avoid double-seeding.
    """
    qubits = getattr(machine, "qubits", None) or {}

    for qid, vals in (populate.get("resonator") or {}).items():
        if qid in qubits and getattr(qubits[qid], "resonator", None) is not None:
            _apply_resonator(qubits[qid].resonator, vals)

    for qid, vals in (populate.get("qubit") or {}).items():
        if qid in qubits:
            _apply_qubit(qubits[qid], vals)

    for qid, vals in (populate.get("flux") or {}).items():
        if qid in qubits and getattr(qubits[qid], "z", None) is not None:
            _apply_flux(qubits[qid].z, vals)

    _apply_pulses(machine, populate.get("pulses") or {})

    if handle_pairs:
        pairs = populate.get("pairs") or {}
        if pairs:
            _apply_pairs(machine, pairs)

def _apply_dual_upconverters(machine, spec):
    """Shared-port CR layout LO surgery (the customer's dual-upconverter trick).

    Every qubit that CONTROLS a cross_resonance/zz_drive line gets a two-entry
    ``upconverters`` dict on its xy MW port: 1 = its own drive LO (whatever
    populate already set), 2 = the CR LO — ``populate.qubit[q].cr_lo_frequency``
    when given, else the mean of its pair partners' ``f_01`` (the customer's
    neighbor-average scheme). The scalar ``upconverter_frequency`` is cleared
    (a port carries one or the other). Runs AFTER apply_populate (LO1/f_01 set)
    and BEFORE _finalize_pair_gates (the CR channel then points at
    ``upconverters/2/frequency``). Returns warnings; never raises.
    """
    warnings: list = []
    if spec.get("cr_port_mode") != "shared_xy":
        return warnings
    pop_q = (spec.get("populate") or {}).get("qubit") or {}
    qubits = getattr(machine, "qubits", None) or {}

    # control -> its CR/ZZ targets, from the pair lines actually in the spec
    partners: dict = {}
    for line in spec.get("lines", []):
        if line.get("line") not in ("cross_resonance", "zz_drive"):
            continue
        try:
            control, target = _parse_pair(line["element"])
        except Exception:  # noqa: BLE001 — malformed element: skip
            continue
        partners.setdefault(str(control), set()).add(str(target))

    def _find_qubit(key):
        if key in qubits:
            return qubits[key]
        for qn, q in qubits.items():
            if str(qn).lstrip("q") == str(key).lstrip("q"):
                return q
        return None

    for control, targets in partners.items():
        q = _find_qubit(control)
        xy = getattr(q, "xy", None)
        port = getattr(xy, "opx_output", None)
        if port is None:
            warnings.append(f"{control}: no xy port — dual upconverter skipped")
            continue
        lo1 = _num(getattr(port, "upconverter_frequency", None))
        lo2 = _num((pop_q.get(f"q{control}") or pop_q.get(str(control)) or {})
                   .get("cr_lo_frequency"))
        if lo2 is None:
            f01s = [_num(getattr(_find_qubit(t), "f_01", None)) for t in targets]
            f01s = [f for f in f01s if f is not None]
            if f01s:
                lo2 = float(int(round(sum(f01s) / len(f01s))))
        if lo1 is None or lo2 is None:
            warnings.append(
                f"q{control}: dual-upconverter LOs unknown (LO1={lo1}, "
                f"LO2={lo2}) — populate the qubit frequencies or set "
                "cr_lo_frequency; the CR drive keeps the single-LO port.")
            continue
        try:
            port.upconverters = {1: {"frequency": lo1}, 2: {"frequency": lo2}}
            port.upconverter_frequency = None
        except Exception as exc:  # noqa: BLE001 — quam parent-quirk guard
            warnings.append(
                f"q{control}: could not install upconverters dict "
                f"({type(exc).__name__}: {exc})")
            continue
        band = getattr(port, "band", None)
        b2 = _band_for(lo2)
        if band is not None and b2 is not None and b2 != band:
            warnings.append(
                f"q{control}: CR LO2 {lo2 / 1e9:.4g} GHz falls in band {b2} "
                f"but the port is band {band} — retune cr_lo_frequency or "
                "the port band.")
    return warnings

def _pin_cores(machine):
    """Customer core-pinning scheme (populate.options.pin_cores): each qubit's
    resonator + xy share a named core ``{q}_{controller}_slot{fem}``; every CR
    channel rides its CONTROL qubit's core. Best-effort, never raises."""
    qubits = getattr(machine, "qubits", None) or {}
    for qname, q in qubits.items():
        for chan_name in ("resonator", "xy"):
            chan = getattr(q, chan_name, None)
            port = getattr(chan, "opx_output", None)
            con = getattr(port, "controller_id", None)
            fem = getattr(port, "fem_id", None)
            if chan is None or con is None or fem is None:
                continue
            try:
                chan.core = f"{qname}_{con}_slot{fem}"
            except Exception:  # noqa: BLE001
                pass
    for pair in (getattr(machine, "qubit_pairs", None) or {}).values():
        qc = getattr(pair, "qubit_control", None)
        xy = getattr(qc, "xy", None)
        core = getattr(xy, "core", None)
        if not core:
            continue
        for chan_name in ("cross_resonance", "zz_drive", "zz"):
            chan = getattr(pair, chan_name, None)
            if chan is not None:
                try:
                    chan.core = core
                except Exception:  # noqa: BLE001
                    pass

def _pulse_class(name):
    """Resolve a pulse class by name across every known module home."""
    import importlib

    for mod_name in _PULSE_HOMES:
        try:
            mod = importlib.import_module(mod_name)
        except ImportError:
            continue
        cls = getattr(mod, name, None)
        if cls is not None:
            return cls
    return None

def _cz_variant_pulses(variant, *, amplitude, duration, smoothing, padding):
    """Build the (qubit_pulse, coupler_pulse, link_attrs) for a CZ *variant*.

    ``coupler_pulse`` is None when the variant carries the whole gate on the qubit
    z line (SNZ / flattop_erf) — safe on fixed OR tunable couplers. ``link_attrs``
    are the shape fields to mirror from the qubit pulse onto the coupler pulse by
    JSON reference (single source of truth). Returns None if the variant needs a
    pulse class missing from EVERY home in this env (caller falls back).
    """
    if variant == "unipolar":
        square = _pulse_class("SquarePulse")
        if square is None:
            return None
        return (square(length=duration, amplitude=amplitude),
                square(length=duration, amplitude=amplitude),
                ("length", "amplitude"))

    if variant == "flattop":
        cls = _pulse_class("_FlatTopGaussianPulse")
        if cls is None:
            return None
        mk = lambda: cls(amplitude=amplitude, flat_length=duration,
                         smoothing_length=smoothing, post_zero_padding_length=padding)
        return (mk(), mk(),
                ("amplitude", "flat_length", "smoothing_length", "post_zero_padding_length"))

    if variant == "bipolar":
        bcls = _pulse_class("_CosineBipolarPulse")
        fcls = _pulse_class("_FlatTopGaussianPulse")
        if bcls is None or fcls is None:
            return None
        # qubit gets the bipolar shape; the coupler mirrors a flat-top (pair_gates).
        return (bcls(amplitude=amplitude, flat_length=duration,
                     smoothing_length=smoothing, post_zero_padding_length=padding),
                fcls(amplitude=amplitude, flat_length=duration,
                     smoothing_length=smoothing, post_zero_padding_length=padding),
                ("amplitude", "flat_length", "smoothing_length", "post_zero_padding_length"))

    if variant == "SNZ":
        cls = _pulse_class("SNZPulse")
        if cls is None:
            return None
        return (cls(amplitude=amplitude, flat_length=duration, t_phi_eff=0.0,
                    padding=padding), None, ())

    if variant == "flattop_erf":
        cls = _pulse_class("ErfSquarePulse")
        if cls is None:
            return None
        return (cls(amplitude=amplitude, flat_length=duration, risetime_samples=16,
                    post_zero_padding_length=padding), None, ())

    return None

def _seed_cz_variant(pair, *, variant="unipolar", amplitude=0.1, duration=100,
                     moving_override=None, smoothing=20, padding=20, vals=None):
    """Seed a CZ macro of *variant* onto *pair* (pair_gates.py ``add_cz`` recipe).

    Flux pulse on the moving (higher-frequency) qubit's z line; on a tunable
    coupler, mirror a matching pulse (with its OWN independent seed) onto the
    coupler line and point the macro's ``coupler_flux_pulse`` at it — the qubit
    and coupler flux pulses are SEPARATE calibration knobs and must not be hard-
    linked into one. The macro key + op names carry the variant and BOTH qubit
    names so the Config Viewer's pair resolver can attribute them. Overwrites the
    same macro key so populate overrides win on a re-run. ``vals``
    (``populate['pairs'][id]``) supplies optional coupler tuning
    (``coupler_interaction_offset`` etc.).

    Unknown / unavailable variants fall back to ``unipolar`` with a warning.
    Returns a warning string if it degraded, else None.
    """
    import inspect

    from quam_builder.architecture.superconducting.custom_gates.flux_tunable_transmon_pair.two_qubit_gates import (  # noqa: E501
        CZGate,
    )

    vals = vals or {}
    qc = getattr(pair, "qubit_control", None)
    qt = getattr(pair, "qubit_target", None)
    if qc is None or qt is None:
        return None

    moving = moving_override
    if moving not in ("control", "target"):
        fc = getattr(qc, "f_01", None) or 0
        ft = getattr(qt, "f_01", None) or 0
        moving = "control" if fc >= ft else "target"
    pair.moving_qubit = moving
    moving_q = qc if moving == "control" else qt
    if getattr(moving_q, "z", None) is None:
        return None

    warning = None
    if variant not in _CZ_VARIANTS:
        warning = (f"CZ variant {variant!r} is not recognized — seeded 'unipolar' "
                   "instead.")
        variant = "unipolar"
    built = _cz_variant_pulses(variant, amplitude=amplitude, duration=duration,
                               smoothing=smoothing, padding=padding)
    if built is None:
        warning = (f"CZ variant {variant!r} needs a pulse class missing from this "
                   "quam_builder install — falling back to 'unipolar'.")
        variant = "unipolar"
        built = _cz_variant_pulses("unipolar", amplitude=amplitude, duration=duration,
                                   smoothing=smoothing, padding=padding)
    qubit_pulse, coupler_pulse, _link_attrs = built

    cn = getattr(qc, "name", None) or getattr(qc, "id", "c")
    tn = getattr(qt, "name", None) or getattr(qt, "id", "t")
    base = f"{cn}_{tn}"
    z = moving_q.z

    # Add the real pulse to the z / coupler operations, and point the macro at
    # them by JSON reference. (Passing op-name strings or bare pulse objects to
    # CZGate either fails to reload — coupler_flux_pulse must be a dict/ref — or
    # never surfaces the pulse on the coupler element. References do both.)
    sig = inspect.signature(CZGate.__init__).parameters
    kwargs = {}

    zop = f"cz_{variant}_flux_pulse_{base}"
    z.operations[zop] = qubit_pulse
    zop_ref = z.get_reference() + f"/operations/{zop}"
    if "flux_pulse_qubit" in sig:
        kwargs["flux_pulse_qubit"] = zop_ref

    if "coupler_flux_pulse" in sig:
        coupler = getattr(pair, "coupler", None)
        if coupler is not None and hasattr(coupler, "operations") and coupler_pulse is not None:
            cop = f"cz_{variant}_coupler_pulse_{base}"
            # Independent coupler pulse (its own literal seed) — the macro points
            # at this op directly. The qubit and coupler flux pulses are separate
            # knobs; hard-linking the coupler op to the qubit op would collapse the
            # two and make the coupler un-tunable.
            coupler.operations[cop] = coupler_pulse
            kwargs["coupler_flux_pulse"] = coupler.get_reference() + f"/operations/{cop}"
            # Coupler bias tuning from populate (decouple / interaction offset, …).
            for attr in ("decouple_offset", "interaction_offset",
                         "flux_point", "settle_time"):
                key = "coupler_" + attr
                if key in vals:
                    try:
                        setattr(coupler, attr, vals[key])
                    except Exception:  # noqa: BLE001 — never fatal
                        pass
        else:
            kwargs["coupler_flux_pulse"] = None

    pair.macros[f"cz_{variant}"] = CZGate(**kwargs)
    return warning

def _cr_flavor(chan) -> str:
    """The installed CR schema flavor of a channel object: ``"rf"`` when it
    carries ``target_qubit_RF_frequency`` (the customer's add-cr-cz-macros
    branch), else ``"lo_if"`` (a08bf66-era ``target_qubit_LO/IF_frequency``
    literals). Field-based, never version-based — versions lie (docs/54)."""
    fields = getattr(type(chan), "__dataclass_fields__", None) or {}
    if "target_qubit_RF_frequency" in fields or hasattr(chan, "target_qubit_RF_frequency"):
        return "rf"
    return "lo_if"

def _import_cr_gate():
    """Import the CRGate macro class, version-robustly across quam_builder
    layouts (it lives in the fixed-transmon-pair tree on the customer's
    add-cr-cz-macros build; some installs expose it under flux_tunable). Returns
    the class or None if this install has no CRGate (e.g. upstream quam 0.5.x,
    where CR is only the channel)."""
    candidates = (
        "quam_builder.architecture.superconducting.custom_gates."
        "fixed_transmon_pair.two_qubit_gates",
        "quam_builder.architecture.superconducting.custom_gates."
        "flux_tunable_transmon_pair.two_qubit_gates",
    )
    for mod_name in candidates:
        try:
            mod = __import__(mod_name, fromlist=["CRGate"])
        except Exception:  # noqa: BLE001 — version-robust: try the next path
            continue
        cls = getattr(mod, "CRGate", None)
        if cls is not None:
            return cls
    return None

def _make_cr_gate(cr_gate_cls, vals):
    """Construct a CRGate, passing only the params the installed class accepts."""
    import inspect

    sig = inspect.signature(cr_gate_cls.__init__).parameters
    kwargs = {}
    for key in ("qc_correction_phase", "qt_correction_phase"):
        if key in sig and key in vals:
            kwargs[key] = vals[key]
    return cr_gate_cls(**kwargs)

def _seed_cr_gate(pair, *, vals=None, shared=False):
    """Seed a full cross-resonance 2Q gate onto *pair* (the customer's
    pair_gates.py ``add_cr`` recipe, adapted to our wiring-built CR channel).

    ``build_quam`` already creates ``pair.cross_resonance`` (a CrossResonanceMW
    with a default ``square`` drive op + the CR gate-level params: drive/cancel
    amplitude-scaling & phase, qc/qt correction phase) from the cross_resonance
    wiring line. This adds what a *usable* CR gate still needs:

      * a ``flattop`` drive op alongside ``square`` (build_quam seeds only square);
      * target-side cancel tones (``cr_square_<pair>`` / ``cr_flattop_<pair>`` on
        the target qubit's xy, length-linked by reference to the cr drive ops;
        used by ``cr_type="direct+cancel*"``);
      * the inferred-IF reference so the drive lands at the target frequency;
      * the ``cr`` gate macro (CRGate) so ``pair.apply("cr", ...)`` dispatches;
      * any populate-supplied frequency / scaling / correction-phase overrides.

    Unlike the customer's fixed-coupler layout, our CR channel owns its allocated
    MW port (from the cross_resonance wiring line), so NO 2nd-upconverter surgery
    on the control xy port is needed — and the control-xy intermediate_frequency
    foot-gun does not apply here.

    Returns a warning string if it had to degrade (no CRGate class), else None.
    """
    vals = vals or {}
    cr = getattr(pair, "cross_resonance", None)
    if cr is None:
        return None  # not a CR-wired pair; nothing to seed

    SquarePulse = _pulse_class("SquarePulse")
    FlatTopGaussianPulse = _pulse_class("FlatTopGaussianPulse")
    if SquarePulse is None or FlatTopGaussianPulse is None:
        # same failure surface as the old direct import
        raise ImportError("SquarePulse/FlatTopGaussianPulse not found in any "
                          "known pulse module home of this env")

    pid = str(getattr(pair, "id", None) or getattr(pair, "name", "") or "")
    drive_amp = vals.get("cr_drive_amplitude", 1.0)
    cancel_amp = vals.get("cr_cancel_amplitude", 0.1)
    sq_len = vals.get("cr_square_length", 100)
    ft_len = vals.get("cr_flattop_length", 16)
    ft_flat = vals.get("cr_flattop_flat_length", 12)

    ops = getattr(cr, "operations", None)
    if ops is not None:
        # square: build_quam seeds one; normalize to the customer seed (full-scale
        # drive, explicit axis_angle). flattop: add it (build_quam omits it).
        ops["square"] = SquarePulse(length=sq_len, amplitude=drive_amp, axis_angle=0.0)
        ops["flattop"] = FlatTopGaussianPulse(
            length=ft_len, amplitude=drive_amp, axis_angle=0.0, flat_length=ft_flat
        )

    warns = []

    # Channel-level CR gate params (defaults already 1.0 / 0.0; honor overrides).
    for attr, key in (
        ("drive_amplitude_scaling", "cr_drive_amplitude_scaling"),
        ("drive_phase", "cr_drive_phase"),
        ("cancel_amplitude_scaling", "cr_cancel_amplitude_scaling"),
        ("cancel_phase", "cr_cancel_phase"),
        ("qc_correction_phase", "qc_correction_phase"),
        ("qt_correction_phase", "qt_correction_phase"),
        ("target_qubit_LO_frequency", "target_qubit_LO_frequency"),
        ("target_qubit_IF_frequency", "target_qubit_IF_frequency"),
    ):
        if key in vals and hasattr(cr, attr):
            try:
                setattr(cr, attr, vals[key])
            except Exception:  # noqa: BLE001
                pass

    # The CR drive must play at the TARGET qubit's frequency. HOW that is
    # encoded depends on the installed CR schema flavor (docs/54):
    #   rf    (add-cr-cz-macros builds): a single target_qubit_RF_frequency —
    #          pointered to the target's xy.RF_frequency so it tracks
    #          recalibration; inferred IF = target_RF − LO.
    #   lo_if (a08bf66 builds): target_qubit_LO/IF_frequency literals (from
    #          populate, else derived from the target's LO + f_01, mirroring
    #          the customer add_cr); inferred IF = target_LO + target_IF − LO.
    # In SHARED mode the channel additionally rides the control's xy port
    # upconverter 2 (the dual-LO layout _apply_dual_upconverters installed).
    # The "#./inferred_intermediate_frequency" reference is pinned ONLY when
    # the quam property actually resolves to a number in-process — else the
    # unresolved "#./..." string ships into the config and qm.open_qm rejects
    # it; leave it None and warn (config stays valid; calibrate later).
    target = getattr(pair, "qubit_target", None)
    control = getattr(pair, "qubit_control", None)
    flavor = _cr_flavor(cr)

    # Gate the upconverter-2 rewiring on the dict ACTUALLY existing —
    # _apply_dual_upconverters legitimately skips a control (no xy port, LOs
    # unknown on a zero-populate build, install raised) with a warning that
    # promises "the CR drive keeps the single-LO port"; rewiring anyway would
    # ship a dangling upconverters/2 reference the config generator rejects.
    _dual = getattr(getattr(getattr(control, "xy", None), "opx_output", None),
                    "upconverters", None)
    if shared and control is not None and _dual:
        try:
            cr.upconverter = 2
            cr.LO_frequency = (control.get_reference()
                               + "/xy/opx_output/upconverters/2/frequency")
        except Exception:  # noqa: BLE001
            pass

    if flavor == "rf":
        if (getattr(cr, "target_qubit_RF_frequency", None) is None
                and target is not None):
            try:
                cr.target_qubit_RF_frequency = (
                    target.get_reference() + "/xy/RF_frequency")
            except Exception:  # noqa: BLE001
                pass
    else:
        if _num(getattr(cr, "target_qubit_LO_frequency", None)) is None:
            tgt_lo = _target_lo(target)
            if tgt_lo is not None:
                try:
                    cr.target_qubit_LO_frequency = tgt_lo
                except Exception:  # noqa: BLE001
                    pass
        if _num(getattr(cr, "target_qubit_IF_frequency", None)) is None:
            tgt_lo = _num(getattr(cr, "target_qubit_LO_frequency", None))
            tgt_f01 = _num(getattr(target, "f_01", None))
            if tgt_lo is not None and tgt_f01 is not None:
                try:
                    cr.target_qubit_IF_frequency = tgt_f01 - tgt_lo
                except Exception:  # noqa: BLE001
                    pass

    # One uniform pin gate for both flavors: the property itself is the oracle
    # (it follows quam references, so the rf flavor's pointer chain and the
    # shared-port upconverters dict are both exercised exactly as the config
    # generator will).
    resolved_if = None
    try:
        resolved_if = cr.inferred_intermediate_frequency
    except Exception:  # noqa: BLE001
        resolved_if = None
    if isinstance(resolved_if, (int, float)) and not isinstance(resolved_if, bool):
        try:
            if getattr(cr, "intermediate_frequency", None) is None:
                cr.intermediate_frequency = "#./inferred_intermediate_frequency"
        except Exception:  # noqa: BLE001
            pass
    else:
        warns.append(
            f"pair {pid}: CR target frequency unknown — populate the qubit "
            "frequencies (or the target frequency fields) so the cross-"
            "resonance drive lands on the target; left intermediate_frequency "
            "unset to keep the generated config valid. Calibrate before use.")

    # Target-side cancel tones, length-linked to the cr drive ops.
    target = getattr(pair, "qubit_target", None)
    txy = getattr(target, "xy", None)
    if txy is not None and getattr(txy, "operations", None) is not None:
        try:
            cref = cr.get_reference()
        except Exception:  # noqa: BLE001
            cref = None
        sq = SquarePulse(length=sq_len, amplitude=cancel_amp, axis_angle=0.0)
        ft = FlatTopGaussianPulse(length=ft_len, amplitude=cancel_amp,
                                  axis_angle=0.0, flat_length=ft_flat)
        if cref:
            sq.length = cref + "/operations/square/length"
            ft.length = cref + "/operations/flattop/length"
            ft.flat_length = cref + "/operations/flattop/flat_length"
        txy.operations[f"cr_square_{pid}"] = sq
        txy.operations[f"cr_flattop_{pid}"] = ft

    # Full customer shape library (populate.pairs[..].cr_shapes == "full"):
    # cosine + gauss drive ops with DRAG params pointer-slaved to the TARGET's
    # x180 (they drive the target's transition), plus their cancel twins.
    # Dedicated-mode default stays "basic" (square+flattop) so existing build
    # goldens don't move; the wizard defaults shared-mode pairs to "full".
    if (str(vals.get("cr_shapes") or "").lower() == "full"
            and ops is not None and txy is not None
            and getattr(txy, "operations", None) is not None):
        DragCosinePulse = _pulse_class("DragCosinePulse")
        DragGaussianPulse = _pulse_class("DragGaussianPulse")
        if DragCosinePulse is None or DragGaussianPulse is None:
            warns.append(
                f"pair {pid}: cr_shapes=full requested but DragCosine/"
                "DragGaussian pulse classes are missing in this env — kept "
                "the basic square+flattop set.")
        else:
            try:
                x180_ref = (target.get_reference()
                            + "/xy/operations/x180_DragCosine")
            except Exception:  # noqa: BLE001
                x180_ref = None
            anh = x180_ref + "/anharmonicity" if x180_ref else 200e6
            alpha = x180_ref + "/alpha" if x180_ref else 0.0
            ops["cosine"] = DragCosinePulse(
                length=sq_len, amplitude=drive_amp, axis_angle=0.0,
                anharmonicity=anh, alpha=alpha, detuning=0)
            ops["gauss"] = DragGaussianPulse(
                length=sq_len, sigma=sq_len / 5, amplitude=drive_amp,
                axis_angle=0.0, anharmonicity=anh, alpha=alpha, detuning=0,
                subtracted=True)
            try:
                cref2 = cr.get_reference()
            except Exception:  # noqa: BLE001
                cref2 = None
            # cancel twins: length/sigma slaved to the drive op; DRAG params
            # relative to the target's own x180 (the customer's #../ idiom)
            cos = DragCosinePulse(
                length=sq_len, amplitude=cancel_amp, axis_angle=0.0,
                anharmonicity="#../x180_DragCosine/anharmonicity",
                alpha="#../x180_DragCosine/alpha", detuning=0)
            gau = DragGaussianPulse(
                length=sq_len, sigma=sq_len / 5, amplitude=cancel_amp,
                axis_angle=0.0,
                anharmonicity="#../x180_DragCosine/anharmonicity",
                alpha="#../x180_DragCosine/alpha", detuning=0, subtracted=True)
            if cref2:
                cos.length = cref2 + "/operations/cosine/length"
                gau.length = cref2 + "/operations/gauss/length"
                gau.sigma = cref2 + "/operations/gauss/sigma"
            txy.operations[f"cr_cosine_{pid}"] = cos
            txy.operations[f"cr_gauss_{pid}"] = gau

    # The cr gate macro (version-robust import; degrade gracefully if absent).
    cr_gate_cls = _import_cr_gate()
    if cr_gate_cls is None:
        warns.append(
            f"pair {pid}: CRGate macro class not found in this quam_builder "
            "install — seeded the CR drive/cancel pulses + channel params but "
            "not the 'cr' macro.")
    else:
        macros = getattr(pair, "macros", None)
        if macros is not None:
            macros["cr"] = _make_cr_gate(cr_gate_cls, vals)
    return "; ".join(warns) if warns else None

def _import_stark_cz_gate():
    """Import the StarkInducedCZGate macro class (same version-robust pattern
    as :func:`_import_cr_gate`); None when this install predates it."""
    candidates = (
        "quam_builder.architecture.superconducting.custom_gates."
        "fixed_transmon_pair.two_qubit_gates",
        "quam_builder.architecture.superconducting.custom_gates."
        "flux_tunable_transmon_pair.two_qubit_gates",
    )
    for mod_name in candidates:
        try:
            mod = __import__(mod_name, fromlist=["StarkInducedCZGate"])
        except Exception:  # noqa: BLE001 — version-robust: try the next path
            continue
        cls = getattr(mod, "StarkInducedCZGate", None)
        if cls is not None:
            return cls
    return None

def _make_stark_cz_gate(cls, vals):
    """Construct a StarkInducedCZGate, passing only accepted params."""
    import inspect

    sig = inspect.signature(cls.__init__).parameters
    kwargs = {}
    for key in ("qc_correction_phase", "qt_correction_phase"):
        if key in sig and key in vals:
            kwargs[key] = vals[key]
    return cls(**kwargs)

def _make_xy_detuned(target, vals):
    """Instantiate the target's ``xy_detuned`` channel (XYDetunedDriveMW),
    riding the target's OWN xy port on upconverter 1 with its drive frequency
    slaved to the xy channel — the Stark-CZ target lobe. None when the class
    is absent from this quam_builder (older builds)."""
    cls = None
    for mod_name in (
            "quam_builder.architecture.superconducting.components.xy_detuned_drive",
            "quam_builder.architecture.superconducting.components"):
        try:
            mod = __import__(mod_name, fromlist=["XYDetunedDriveMW"])
        except Exception:  # noqa: BLE001 — try the next home
            continue
        cls = getattr(mod, "XYDetunedDriveMW", None)
        if cls is not None:
            break
    if cls is None:
        return None
    xy = getattr(target, "xy", None)
    port = getattr(xy, "opx_output", None)
    if xy is None or port is None:
        return None
    try:
        xref = xy.get_reference()
        return cls(
            opx_output=xref + "/opx_output",
            upconverter=getattr(xy, "upconverter", 1) or 1,
            xy_RF_frequency=xref + "/RF_frequency",
            xy_intermediate_frequency=xref + "/intermediate_frequency",
            detuning=(vals or {}).get("zz_detuning", -30e6),
        )
    except Exception:  # noqa: BLE001 — field drift across builds
        return None

def _seed_zz_gate(pair, *, vals=None, shared=False):
    """Seed the Stark-induced-CZ (ZZ drive) family onto *pair* — the customer's
    commented-out populate block, productized (docs/54).

    ``build_quam`` creates ``pair.zz_drive`` (ZZDriveMW + a square op) from the
    zz wiring line. This adds: the flattop drive op, detuning + target LO/IF,
    the shared-port LO pointer (upconverter 2 on the control's xy port), the
    target's ``xy_detuned`` twins (``zz_square_<pid>`` / ``zz_flattop_<pid>``,
    length-linked) — the qubit class must carry the ``xy_detuned`` field
    (FixedFrequencyZZDriveTransmon; plain transmons degrade with a warning) —
    and the ``stark_cz`` macro. Returns a warning string or None.
    """
    vals = vals or {}
    zz = getattr(pair, "zz_drive", None)
    if zz is None:
        zz = getattr(pair, "zz", None)     # branch-tip field rename
    if zz is None:
        return None                        # not a zz-wired pair

    SquarePulse = _pulse_class("SquarePulse")
    FlatTopGaussianPulse = _pulse_class("FlatTopGaussianPulse")
    if SquarePulse is None or FlatTopGaussianPulse is None:
        raise ImportError("SquarePulse/FlatTopGaussianPulse not found in any "
                          "known pulse module home of this env")

    warns = []
    pid = str(getattr(pair, "id", None) or getattr(pair, "name", "") or "")
    zz_amp = vals.get("zz_drive_amplitude", 1.0)
    ft_len = vals.get("zz_flattop_length", 100)
    ft_flat = vals.get("zz_flattop_flat_length", 84)

    ops = getattr(zz, "operations", None)
    if ops is not None:
        ops["square"] = SquarePulse(length=100, amplitude=zz_amp, axis_angle=0.0)
        ops["flattop"] = FlatTopGaussianPulse(
            length=ft_len, amplitude=zz_amp, axis_angle=0.0, flat_length=ft_flat)

    if hasattr(zz, "detuning"):
        try:
            zz.detuning = vals.get("zz_detuning", -30e6)
        except Exception:  # noqa: BLE001
            pass

    control = getattr(pair, "qubit_control", None)
    target = getattr(pair, "qubit_target", None)
    # Same dict-exists gate as _seed_cr_gate: never point at upconverters/2
    # on a port _apply_dual_upconverters skipped (single-LO port kept).
    _dual = getattr(getattr(getattr(control, "xy", None), "opx_output", None),
                    "upconverters", None)
    if shared and control is not None and _dual:
        try:
            zz.upconverter = 2
            zz.LO_frequency = (control.get_reference()
                               + "/xy/opx_output/upconverters/2/frequency")
        except Exception:  # noqa: BLE001
            pass
    # target LO/IF: numeric derivation from the target (customer idiom)
    if hasattr(zz, "target_qubit_LO_frequency"):
        if _num(getattr(zz, "target_qubit_LO_frequency", None)) is None:
            tgt_lo = _target_lo(target)
            if tgt_lo is not None:
                try:
                    zz.target_qubit_LO_frequency = tgt_lo
                except Exception:  # noqa: BLE001
                    pass
        if (_num(getattr(zz, "target_qubit_IF_frequency", None)) is None
                and _num(getattr(zz, "target_qubit_LO_frequency", None)) is not None
                and _num(getattr(target, "f_01", None)) is not None):
            try:
                zz.target_qubit_IF_frequency = (
                    float(target.f_01) - float(zz.target_qubit_LO_frequency))
            except Exception:  # noqa: BLE001
                pass
    try:
        inferred = zz.inferred_intermediate_frequency
        if isinstance(inferred, (int, float)) and getattr(
                zz, "intermediate_frequency", None) is None:
            zz.intermediate_frequency = "#./inferred_intermediate_frequency"
    except Exception:  # noqa: BLE001
        warns.append(
            f"pair {pid}: ZZ drive frequency chain unresolved — left "
            "intermediate_frequency unset to keep the config valid.")

    # Target-lobe twins on xy_detuned. The channel has NO wiring line type in
    # any qualang-tools (verified) — it must be created by direct assignment
    # onto the target qubit, riding the target's own xy port (the customer's
    # commented-out populate does exactly this). Only qubit classes with the
    # field can hold it (FixedFrequencyZZDriveTransmon; plain transmons
    # degrade with a warning).
    xy_det = getattr(target, "xy_detuned", None)
    if xy_det is None and target is not None and hasattr(target, "xy_detuned"):
        xy_det = _make_xy_detuned(target, vals)
        if xy_det is not None:
            try:
                target.xy_detuned = xy_det
            except Exception:  # noqa: BLE001 — type-union guard (docs/54 R4)
                xy_det = None
    if xy_det is None:
        warns.append(
            f"pair {pid}: target has no xy_detuned channel (qubit class "
            "without the ZZ-drive field, or the channel class is missing) — "
            "Stark-CZ target-lobe tones skipped; the gate drives the control "
            "lobe only.")
    elif getattr(xy_det, "operations", None) is not None:
        try:
            zref = zz.get_reference()
        except Exception:  # noqa: BLE001
            zref = None
        sq = SquarePulse(length=100, amplitude=0.1, axis_angle=0.0)
        ft = FlatTopGaussianPulse(length=ft_len, amplitude=0.1,
                                  axis_angle=0.0, flat_length=ft_flat)
        if zref:
            sq.length = zref + "/operations/square/length"
            ft.length = zref + "/operations/flattop/length"
            ft.flat_length = zref + "/operations/flattop/flat_length"
        xy_det.operations[f"zz_square_{pid}"] = sq
        xy_det.operations[f"zz_flattop_{pid}"] = ft

    stark_cls = _import_stark_cz_gate()
    if stark_cls is None:
        warns.append(
            f"pair {pid}: StarkInducedCZGate class not found in this "
            "quam_builder — seeded the ZZ drive but not the 'stark_cz' macro.")
    else:
        macros = getattr(pair, "macros", None)
        if macros is not None:
            macros["stark_cz"] = _make_stark_cz_gate(stark_cls, vals)
    return "; ".join(warns) if warns else None

def _cz_order_warning(quam_id, pair, vals):
    """Wizard-contract safety net: CZ pairs arrive oriented control = the
    higher-f_01 qubit (the wizard's czAutoOrient flips the stored spec pair as
    frequencies are typed). NEVER flips anything here — reordering after
    ``apply_populate`` would rename the QUAM pair id out from under the
    ``populate.pairs`` matching and every element/op name. Just surfaces a
    warning in ``_result.json`` when a backwards CZ pair reaches the build
    (old draft / hand-written spec) and the user didn't pin the order with
    ``cz_order: manual``. Physics stays correct either way — the flux pulse
    plays on the higher-frequency (moving) qubit regardless of labels.
    """
    if (vals or {}).get("cz_order") == "manual":
        return None
    try:
        fc = float(getattr(getattr(pair, "qubit_control", None), "f_01", None) or 0)
        ft = float(getattr(getattr(pair, "qubit_target", None), "f_01", None) or 0)
    except (TypeError, ValueError):
        return None
    if fc and ft and ft > fc:
        return (
            f"pair {quam_id}: target f_01 ({ft / 1e9:.4g} GHz) is higher than "
            f"control ({fc / 1e9:.4g} GHz) — the wizard orients CZ pairs "
            "control = higher-frequency qubit. The flux pulse still plays on "
            "the higher-frequency (moving) qubit; set "
            f"populate.pairs['{quam_id}'].cz_order = 'manual' to keep this "
            "order silently."
        )
    return None

def _finalize_pair_gates(machine, spec, pair_gate):
    """Add the wizard's chosen 2Q-gate macros (CR / CZ fixed / CZ tunable).

    ``cz_fixed`` creates the otherwise-missing pairs first (no coupler wiring
    line). ``cr`` / ``cz_tunable`` pairs already exist from their wiring lines.
    ``populate['pairs'][<id>]`` overrides per-pair seed params (cz_amplitude /
    cz_interaction_duration / cz_variant / moving_qubit; cr_* drive/cancel/phase).
    Returns a list of warning strings (empty when every seed was exact).
    """
    warnings: list = []
    qubits = getattr(machine, "qubits", None) or {}
    qpairs = getattr(machine, "qubit_pairs", None)
    if qpairs is None:
        return warnings
    populate_pairs = (spec.get("populate") or {}).get("pairs") or {}
    # populate.pairs may be keyed by the wizard's "control-target" spec id
    # ("q1-q2") or already by the QUAM pair id ("q1-2"); the qpairs keys below are
    # QUAM pair ids, so normalize both forms onto the QUAM id (else wizard-entered
    # per-pair overrides silently never reach the seed).
    norm_pairs = dict(populate_pairs)
    for _k, _v in populate_pairs.items():
        try:
            norm_pairs.setdefault(_quam_pair_id(_k), _v)
        except Exception:  # noqa: BLE001 — a malformed key just isn't normalized
            pass

    if pair_gate == "cz_fixed":
        try:
            from quam_builder.architecture.superconducting.qubit_pair.flux_tunable_transmon_pair import (  # noqa: E501
                FluxTunableTransmonPair,
            )
        except Exception:  # noqa: BLE001 — version-robust: skip if the class moved
            FluxTunableTransmonPair = None
        for spec_pair in spec.get("qubit_pairs") or []:
            parsed = _norm_pair_qubits(spec_pair)
            if not parsed:
                continue
            control, target, quam_id = parsed
            if quam_id in qpairs:
                continue
            qc = qubits.get(control)
            qt = qubits.get(target)
            if qc is None or qt is None or FluxTunableTransmonPair is None:
                continue
            qpairs[quam_id] = FluxTunableTransmonPair(
                id=quam_id,
                qubit_control=qc.get_reference(),
                qubit_target=qt.get_reference(),
            )

    shared = (spec.get("cr_port_mode") == "shared_xy")
    for quam_id, pair in list(qpairs.items()):
        vals = norm_pairs.get(quam_id) or {}
        if pair_gate == "cr":
            w = _seed_cr_gate(pair, vals=vals, shared=shared)
            zw = _seed_zz_gate(pair, vals=vals, shared=shared)
            if zw:
                warnings.append(zw)
        else:
            ow = _cz_order_warning(quam_id, pair, vals)
            if ow:
                warnings.append(ow)
            w = _seed_cz_variant(
                pair,
                # "" is the wizard's "use default" sentinel == unipolar.
                variant=vals.get("cz_variant") or "unipolar",
                amplitude=vals.get("cz_amplitude", 0.1),
                duration=vals.get("cz_interaction_duration", 100),
                moving_override=vals.get("moving_qubit"),
                vals=vals,
            )
        if w:
            warnings.append(w)

    # Warn on populate.pairs keys that match no built pair (typos / removed pairs)
    # so a silently-dropped per-pair override is visible in _result.json.
    qpair_ids = set(qpairs.keys())
    for k in populate_pairs:
        norm = k
        try:
            norm = _quam_pair_id(k)
        except Exception:  # noqa: BLE001
            pass
        if k not in qpair_ids and norm not in qpair_ids:
            warnings.append(
                f"populate.pairs['{k}']: no matching qubit pair was built — the "
                "per-pair overrides under this key were ignored.")
    return warnings

def _split_port_pointer(ptr):
    """Parse a wiring port reference into its path segments.

    Returns the segments between ``#/`` and the end, or ``None`` if the
    input is not a valid absolute pointer.

    >>> _split_port_pointer("#/ports/mw_outputs/con1/1/1")
    ['ports', 'mw_outputs', 'con1', '1', '1']
    """
    if not isinstance(ptr, str) or not ptr.startswith("#/"):
        return None
    segs = ptr[2:].split("/")
    return segs if all(segs) else None

def _walk_state(state, segs):
    """Resolve a list of path segments against a state dict.

    Returns the dict at ``state[segs[0]][segs[1]]...[segs[-1]]`` or
    ``None`` if any segment is missing or a non-dict is encountered
    before the last segment.
    """
    cur = state
    for s in segs:
        if not isinstance(cur, dict) or s not in cur:
            return None
        cur = cur[s]
    return cur

def _link_input_downconverters_to_outputs(state_path, wiring_path):
    """Rewrite each MW input port's ``downconverter_frequency`` so it is a
    JSON pointer to its paired MW output port's ``upconverter_frequency``.

    Why: hardware-wise the readout output and input on a given MW-FEM port
    share a single physical local oscillator.  When the wizard subprocess
    persists them as two independent floats, the constraint is implicit
    and silently drifts the moment anyone edits one side.  Encoding the
    input as the pointer ``#/ports/mw_outputs/<con>/<slot>/<port>/upconverter_frequency``
    makes the constraint explicit and lets the existing pointer resolver
    keep the two in lockstep across all future reads/edits.

    Idempotent.  No-op when the wiring has no readout channels, when the
    output has no ``upconverter_frequency`` set, or when the input is
    already a pointer.  ``band`` is intentionally left as a literal —
    matches the example-9q-rack encoding already in production.
    """
    state_path = Path(state_path)
    wiring_path = Path(wiring_path)
    if not state_path.exists() or not wiring_path.exists():
        return

    with open(state_path, "r", encoding="utf-8") as fh:
        state = json.load(fh)
    with open(wiring_path, "r", encoding="utf-8") as fh:
        wiring = json.load(fh)

    qubits = (wiring.get("wiring") or {}).get("qubits") or {}
    if not qubits:
        return

    # Build a set of (input_segs, output_segs) for every readout channel.
    # Using a set dedups the common case where many qubits share a feedline.
    pairs: set[tuple[tuple[str, ...], tuple[str, ...]]] = set()
    for qname, qdata in qubits.items():
        rr = (qdata or {}).get("rr") or {}
        out_segs = _split_port_pointer(rr.get("opx_output"))
        in_segs = _split_port_pointer(rr.get("opx_input"))
        if not out_segs or not in_segs:
            continue
        pairs.add((tuple(in_segs), tuple(out_segs)))

    changed = False
    for in_segs_t, out_segs_t in pairs:
        in_segs = list(in_segs_t)
        out_segs = list(out_segs_t)

        out_port = _walk_state(state, out_segs)
        if not isinstance(out_port, dict):
            continue
        up = out_port.get("upconverter_frequency")
        # If the output has no concrete upconverter we can't build a link;
        # also skip if it's already a pointer (no real source value here).
        if up is None or isinstance(up, str):
            continue

        in_port = _walk_state(state, in_segs)
        if not isinstance(in_port, dict):
            continue

        existing = in_port.get("downconverter_frequency")
        pointer = "#/" + "/".join(out_segs) + "/upconverter_frequency"
        if existing == pointer:
            continue  # already linked

        in_port["downconverter_frequency"] = pointer
        changed = True

    if not changed:
        return

    # Atomic write so a partial state.json never lands on disk if the
    # process is killed mid-write.  os.replace is atomic on every OS the
    # generator runs on (Linux/macOS/Windows).
    tmp = state_path.with_suffix(state_path.suffix + ".lo-link.tmp")
    with open(tmp, "w", encoding="utf-8") as fh:
        json.dump(state, fh, indent=4)
    os.replace(tmp, state_path)

# =============================== run ==================================
machine = QuamCls.load()
_spec = {"populate": POPULATE, "qubit_pairs": QUBIT_PAIRS,
         "cr_port_mode": CR_PORT_MODE, "lines": PAIR_LINES}
apply_populate(machine, POPULATE, handle_pairs=(PAIR_GATE == ""))
for _w in _apply_dual_upconverters(machine, _spec):
    print(f"WARNING: {_w}", file=sys.stderr)
if PAIR_GATE in ("cz_fixed", "cz_tunable", "cr"):
    for _w in _finalize_pair_gates(machine, _spec, PAIR_GATE):
        print(f"WARNING: {_w}", file=sys.stderr)
if (POPULATE.get("options") or {}).get("pin_cores"):
    _pin_cores(machine)
machine.save()

# Readout-LO constraint lock (the wizard's post-save fix-up): each MW
# input port's downconverter_frequency becomes a JSON pointer to its
# paired output port's upconverter_frequency (one physical LO).
_link_input_downconverters_to_outputs(
    Path(STATE_DIR) / "state.json", Path(STATE_DIR) / "wiring.json")

print(f"populated + saved: {len(machine.qubits)} qubits, "
      f"{len(machine.qubit_pairs)} pairs, "
      f"macros: { {p: sorted(m.macros) for p, m in machine.qubit_pairs.items()} }")
