#!/usr/bin/env python
"""demo — step 3/3: sanity-run machine.generate_config().

Generated by QUAM State Manager (2026-01-01).

    python 03_generate_config.py [STATE_DIR] [--dump config.json]
"""
import json
import os
import sys

args = [a for a in sys.argv[1:] if not a.startswith('--')]
STATE_DIR = args[0] if args else "./quam_state"
os.environ["QUAM_STATE_PATH"] = os.path.abspath(STATE_DIR)

from quam import QuamRoot  # noqa: F401  (ensures quam is importable)
from quam_builder.architecture.superconducting.qpu import (
    FluxTunableQuam, FixedFrequencyQuam,
)

# Load with whichever architecture the state carries.
try:
    machine = FluxTunableQuam.load()
except Exception:  # noqa: BLE001 — fixed-frequency chip
    machine = FixedFrequencyQuam.load()

cfg = machine.generate_config()
print(f"generate_config() OK: {len(cfg['elements'])} elements, "
      f"{len(cfg.get('controllers', {}))} controllers")

if '--dump' in sys.argv:
    i = sys.argv.index('--dump')
    dst = sys.argv[i + 1] if len(sys.argv) > i + 1 else 'config.json'
    with open(dst, 'w', encoding='utf-8') as fh:
        json.dump(cfg, fh, indent=2, default=str)
    print(f'config dumped to {dst}')
